### ISSUE TITLE
Websocket free interface (additionally)

### ISSUE THREAD

**Issue by escoand** [volumio/Volumio2-UI#107]
I tried upcycle my old Kindle and opened volumio UI in the browser but this device has no websocket implementation. Maybe there are more device with this disadvantage.

So there could be a static page which reloads 
 30 seconds by HTML meta tag. It should be enough to show the current playing song and the next in the playlist.

The kindles previous/next page buttons could eventually be used for interaction...

**Comment by volumio** [comment]
Yes, in the future we were thinking to integrate a REST fallback for older browsers...
