### ISSUE TITLE
Pre RC2 Bits

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#115]
Just notes of things that should be fixed before RC2
<strike>-No feedback when saving Spotify settings, needs some kind of confirmation</strike>
-Spop name should be Spotify in installed plugins list
<strike>-'Back to Plugins' button is horrible with terrible placement</strike>
<strike>-Spotify password input should be a password field not text</strike>
<strike>-Spotify settings has the page title 'Network' which makes no sense</strike>
-Plugin Uninstall modal could do with some text in it, or it just looks weird
-Cannot uninstall spotify plugin
<strike>-Still have the problem with plugin switches being in a indeterminate state</strike>
-No way to uninstall a plugin that has been uploaded like the brutefir plugin
<strike>-Wireless network list still has an issue with the last item in the list being 'Network Name' with a connect button (this is a desiderata, to connect to hidden network)</strike>
<strike>-Add alarm modal is still a horrible mess of different vertical alignments</strike>
-Move shuffle/random back to the playback window, it does not work well from a UX point of view on the queue page

**Comment by balbuze** [comment]
- Add a software volume control for dac without (ess9023, pcm 5022 etc...)
- Album art not displayed in mobile UI with ' in name / title /artist/album (I have to test if it comes from file name or metadata

**Comment by gkkpch** [comment]
Appearance Menu:
- Dragging an image to the drop zone aborts & restarts volumio
- Selecting an image in the appearance menu works without issues

**Comment by gkkpch** [comment]
Spotify (Odroid)
- Can configure and browse my playlists
- Starts playing when requested, but no sound. /etc/spopd.conf shows "hw:0" 
  (Default HDMI, can't verify)

**Comment by apinner** [comment]
-Format icon assumes that every format has an icon which we don't, which means when there is no icon we just get a missing image. Needs to default to just the format name in text if we are missing the icon.

**Comment by apinner** [comment]
This should probably be fixed before RC2 as well.. The multi room dock issue. I recorded a quick vid to show the problem.

https://www.youtube.com/watch?v=PgkV1Gdnz5s

I have been working on my dev pi and had to reboot it a number of times. Each reboot = a new entry in the multi room dock. To the point it just got ridiculous! @kurtommy even puts an appearance in the video!

**Comment by balbuze** [comment]
on mobile UI, setting menu is too long on a small  screen (and no scrolling available) 
![screenshot_2016-06-07-21-33-48](https://cloud.githubusercontent.com/assets/12850139/15872096/f49d4198-2cf7-11e6-95c9-f6823e3c39ab.png)

**Comment by volumio** [comment]
@balbuze, we've just fixed that!

**Comment by balbuze** [comment]
Yes! I see that ! ;-)

**Comment by balbuze** [comment]
With last img and Ui (volumio-0.894-2016-06-15-pi.img) album art is not always displayed. In some album containing a folder.jpg file, it is not displayed. It was working préviously.

**Comment by balbuze** [comment]
In fact the file is folder is not used... In the screenshot we see this is not the same file 
![album-diff](https://cloud.githubusercontent.com/assets/12850139/16130248/8ec4f52e-3408-11e6-89b7-a08921c940f0.png)

**Comment by apinner** [comment]
Just noticed someone added a commented on my point "Wireless network list still has an issue with the last item in the list being 'Network Name' with a connect button"

If that's the case, can we make that a bit clearer? Maybe change it to 'Connect to hidden network'?

**Comment by volumio** [comment]
Absolutely!

**Comment by balbuze** [comment]
In mobile UI, when a select list is available, like output seector, it opens the keyboard. I kown I reported it in a other tread but as it is still here...
In mobile Ui you can't upload a plugin because menu doesn't display the tab

**Comment by apinner** [comment]
Wasn't that an Angular bug?

**Comment by balbuze** [comment]
I remember this is the answer you made. But I don't know what cause this...I think you are more competent than me ;-)

**Comment by apinner** [comment]
I'm not sure its something we can fix, it's a an actual bug in the Angular system.

**Comment by balbuze** [comment]
what a pity !

**Comment by davze** [comment]
In RC2 playing a custom webradio does not work for me. And the option to delete the custom webradios is gone?
