### ISSUE TITLE
Open ource Design documentation and Iteration

### ISSUE THREAD

**Issue by alfatreze** [volumio/Volumio2-UI#137]
Could we have and open sourced design documentation and assets (moodboards, wireframes, patterns, templates, logos, icons, etc) so any contributor could have access and contribute here as well?

This way the assets, documentation and guidelines can developed alongside the code.

**Comment by volumio** [comment]
Yes, absolutely. But it will take time, since all our efforts are in coding as of now.
If you could set up something, like an open source doc system, any help would be welcome !

**Comment by alfatreze** [comment]
I'll look at it, thinking of using frontify for now: https://frontify.com/styleguide.

Later on Styleguide or similar: http://livingstyleguide.devbridge.com/ and invision or marvel for wireframes and mockups.

**Comment by apinner** [comment]
We have already used Invision for mockups during the initial stages of putting together the UI. https://invis.io/655UDYPBT

**Comment by alfatreze** [comment]
Thks, already did take a peek, and can definitely see some improvements that can be made, but i'll give it time and consider changes carefully and with method :D.

I'll probably start by making quick wireframes from it and iterating from there.

The one thing that really bothers me is the UI for browsing, the separation between the lines (especially when contrasting with light backgrounds) and wide empty spaces are quite disrupting. Shortening and possibly displaying album artwork on the side would certainly work better. Not to mention grid views, that I have seen referred somewhere.
