### ISSUE TITLE
v1 style library browse

### ISSUE THREAD

**Issue by ying-w** [volumio/Volumio2-UI#140]
Feature request: In v1.55 clicking on browse will bring up a menu (similar to foobar's library) where music is sorted by artist/album and clicking on each subheading would filter the songs.

Currently in RC2, if music is on a NAS, Instead of seeing the music after clicking browse, you'll have to click on Music Library -> NAS -> (NAS folder name) -> unsorted list of music

I was wondering if it would be possible to bring back pieces of the old interface (less clicks to get a list of artists/albums) and/or move favorites/webradio into their own tab

**Comment by kuchendieb** [comment]
jep, this was indeed a pretty neat feature. this would make browsing your collection a lot more fun.

**Comment by PierreMardon** [comment]
Just tried v2 and never tried v1 and I think it's the main UX lack : even with searching, when the results contains artists or albums, it's confusing not being able to see the related titles without having to add all of them to the queue.
Also in an ideal Volumio, every reference to artist / album would be clickable and would take you to a filtered /browse view. This indirectly requires any browse view containing a list of titles (like the content of an album) to have the option to play all the tracks in it (play all / enqueue all / clear and play all...).
