### ISSUE TITLE
duplicates should be excluded from queue and other bugs from double clicking

### ISSUE THREAD

**Issue by ying-w** [volumio/Volumio2-UI#142]
when double clicking on a song multiple times in /browse (by clicking on browse or by clicking on 'more by this artist'), the song is queued up multiple times. I do not believe this is the intended behavior but rather ignore adding the same song (or list of songs by the same artist). 

when double clicking on songs in the queue (to skip around) sometimes songs get removed from queue before they are finished playing

I've run into these issue on RC2

**Comment by volumio** [comment]
Fixed
