### ISSUE TITLE
UI stuck in loading state on local browser

### ISSUE THREAD

**Issue by freddy-se** [volumio/Volumio2-UI#143]
While everything is working fine when accessing the UI from a remote machine, there are some problems when trying from a local browser.

My setup:
- Raspberry Pi 3
- Waveshare 7'' touch display
- Autostarting Chromium 50 to display http://localhost:3000

Problem:
The UI is stuck in loading state (div#overlay with animated circle). Chromium throws error "Failed to load resource: net::ERR_CONNECTION_REFUSED, http://localhost/api/host"

My first guess is that port 3000 is missing in some internal link. Is there any other information I can provide to help with that issue?

**Comment by volumio** [comment]
It seems that's failing to retrieve the api IP address (probably because we forward 3000 to localhost only from the outside).
So to circumvent this, Create a file in:
/volumio/http/www/src/app/local-config.json

and write inside

{
  "localhost": "http://127.0.0.1"
}

Let me know how it goes

**Comment by freddy-se** [comment]
In my case the file is in /volumio/http/www/app/local-config.json (without the /src/ part)
After changing to
> {
"localhost": "http://127.0.0.1:3000"
}

the UI is working. Without the port number it still was stuck in loading state.
I don't have the time right now for further testing but so far it looks good. Thanks a lot!
