### ISSUE TITLE
Play button in radio mode 

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2-UI#176]
Playing a radiostation the stop/play button doesn´t work (allways in play state).

**Comment by apinner** [comment]
Solution? https://github.com/volumio/Volumio2/issues/619#issuecomment-236557001

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/f6c21ca2d0b45c8fd0b66ffc9877722d7ea9b2a5
and https://github.com/volumio/Volumio2-UI/commit/f73369af064e4d040af70004317d86817482cc9f
