### ISSUE TITLE
mount share

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#18]
I apply the last update from webUI. and also a git pull of /volumio. Now the config for my music came back to the version before mpasteur 's PR (except the size )! Missing field to configure properly the mount...

**Comment by mpasteur** [comment]
hi balbuze. i did the test and for me dist (the sumbmodule in http/www) is correctley updated.
the dist branch was updated at 10:30 this morning can you make a "git log" in http/www 
It should display:

commit b51749491b6ca2fcda8492d470e120bf024c1342
Author: Volumio <info@volumio.org>
Date:   Tue Jan 19 10:31:53 2016 +0000

    Deploy to Dist Branch

**Comment by balbuze** [comment]
@mpasteur this commit does not appears. My system is to date (git pull today)...

**Comment by balbuze** [comment]
I built a new image last night with the last build script and this one is ok. but I can t update my other with the good ui...

**Comment by volumio** [comment]
Due to the nature of the updater, if you manually changed one file , it will persist across reboots. so probably you're getting old files because you edited them...

**Comment by balbuze** [comment]
ok now
