### ISSUE TITLE
Plugin management UI

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2-UI#203]
Spotify plugin was installed in early releases.
Now with recent releases, like 1.005, plugin can not be disabled or uninstalled:
- disable switch flips, but UI shows still active
- changing panel and coming back in plugin view, switch is back to on
- uninstall procedure does not seem to do anything

**Comment by paviro** [comment]
Just installed v2 from the website and I can't find a uninstall button for plugins anywhere.

**Comment by macmpi** [comment]
not relevant anymore, closing
