### ISSUE TITLE
2.000 Playback option display issue

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2-UI#207]
Value not found title & button unavailable

![screen shot 2016-10-14 at 16 30 43](https://cloud.githubusercontent.com/assets/16296055/19391240/fb9a341c-922b-11e6-90a0-b117b8ea442a.png)

**Comment by jo-me** [comment]
Hey, in 2.001, this seems to be fixed..  or at least it does not appear in my setup:

![image](https://cloud.githubusercontent.com/assets/10351272/19512927/7d4835f2-95ee-11e6-8373-a0fb6f1273a3.png)

**Comment by macmpi** [comment]
Was not in my original 2.001 setup, constructed by numerous updates from 0.923.
However started fresh with brand new 2.001, and all is good.
Can be closed
