### ISSUE TITLE
Missing "Add to queue" on cuesong popup item 

### ISSUE THREAD

**Issue by syfre** [volumio/Volumio2-UI#209]
In the browse table on a cuesong the popup menu don't display "Add to queue", "Add to playlist","Add to favorite" ... like song items do.

In browse.controller.js there are many test on item.type =="song"  with missing test on "cuesong", example : 

  showAddToQueueButton(item) {
    let ret = item.type === 'folder' || item.type === 'song' ||
        item.type === 'mywebradio' || item.type === 'webradio' ||
        item.type === 'playlist';
    return ret;
}

**Comment by volumio** [comment]
This is on purpose, since handling single songs on cue files is nearly impossible...
