### ISSUE TITLE
Play / Stop button not refreshing correctly

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2-UI#212]
1) Open the Web Interface 
2) Start web radio station
3) Press stop in the top bar  ==> web radio playback stops, button switches to play button
ok so far, but now:
4) Press play ==> web radio playback starts again, but the button does not switch to stop button. Also, the left circle on the playback screen is empty now. Previously, it showed "webradio".
In this state it is not possbile to stop the stream anymore.

I'm using volumio 2.001 on a raspberry 1. 

The picture shows the last state. Stream is playing but UI is not reflecting this.

![image](https://cloud.githubusercontent.com/assets/10351272/19419725/e5e839bc-93dd-11e6-8f20-8279b3d2be39.png)

**Comment by peEtric** [comment]
Having more or less the same issue, but I would describe it as follow (using the beautiful volumio UI):
- Starting any Web-Radio
- Volumio plays it nicely
- After 0 to 20min (it varies), the playback view completly looses focus and I can't stop the Webradio, unless I start playing any non-Webradio file/thing

Some additional info:
- It doesn't matter, which client (PC web, smartphone web, tablet...) I use or if I switch the controlling device 
- It doesn't matter, how the queue looks like (empty, other mp3 files, other webradios, mixed, ...)
- A restart doesn't solve the problem
- It doesn't matter which Webradio (own or one which was available in the directory)
   - More details: 
        - My favourite webradio (http://stream.srg-ssr.ch/drs3/mp3_128.m3u, http://stream.srg-ssr.ch/drs3/aacp_96.m3)
        - Favourite Webradio from directory: Energy Zurich - Zurich (From Country - Switzerland)
- If I check BubbleUPnP with APP on Android, I see the correct Webradio name and I can stop it without any problems

-----
If somebody could give me a quick start in which classes / methods I should have a look to possible find the error, I'm going to debug it next year....
