### ISSUE TITLE
Mixer type & mixer control name settings not working

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2-UI#217]
In the settings screen "playback options" the group "volume options" is not behaving correctly. 
"Mixer Type" and "Mixer control name" show an empty combobox. If I click on either of them, the box disappears.

I'm running volumio 2.001 on a raspberry 1. 

![image](https://cloud.githubusercontent.com/assets/10351272/19513047/d6c51636-95ee-11e6-8dc9-f5fdfdabd832.png)

**Comment by Jotam** [comment]
+1 
I have the same problem here on a Raspi 3.

**Comment by volumio** [comment]
did you guys come from a fresh install or upgrade? tell me which output device are you using, does it have hardware mixer?

**Comment by Jotam** [comment]
I upgrade from 2.0.something...
I'm running volumio on raspi 3 with Hifiberry Amp+

**Comment by jo-me** [comment]
At the time of writing I did not have any DAC connected. Fresh install of 2.001
