### ISSUE TITLE
New Libarary view "Recently added"

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2-UI#220]
In order to identify new music that has been added to the library more easily, it would be cool to have a view in the library root such as "Recently added" that shows the library items in a descending order of the date they were added.

The recently added items are probably the most likely things to be played in the near future, so why not make them more accessible. 

The corresponding forum thread is here: https://volumio.org/forum/new-libarary-view-recently-added-t4852.html

**Comment by mikerspencer** [comment]
I'm really keen for this. What would it cost to add the feature?

**Comment by luisschmui** [comment]
This would be a great feature (and so think [many people](https://community.volumio.org/t/new-libarary-view-recently-added/4464/17)).
Any reason why this was closed?
