### ISSUE TITLE
IQaudIO "Value not found!

### ISSUE THREAD

**Issue by paviro** [volumio/Volumio2-UI#225]
Latest Volumio version:
![iqaudio](https://cloud.githubusercontent.com/assets/992826/19619450/276e0568-9868-11e6-9d8f-d1726ea232da.png)

**Comment by volumio** [comment]
Which version number?
Did it automatically detect the dac? Did you reboot?

**Comment by paviro** [comment]
2.001
No I had to set it manually.
Yes :)

**Comment by paviro** [comment]
2.001 No it did not I had to enable it manually. Yes I did :)

**Comment by paviro** [comment]
Well that Mail did surely arrive late 😅
