### ISSUE TITLE
M4A bitrate displayed as NaN

### ISSUE THREAD

**Issue by rretsiem** [volumio/Volumio2-UI#232]
All my M4A files from a NAS with metadata (iTunes) showing a bitrate of NaN, MP3 files work fine.
Files are from iTunes catalog AAC at 256kbit/s.

<img width="694" alt="m4a_nan-bits" src="https://cloud.githubusercontent.com/assets/248836/19823549/7183d1e0-9d69-11e6-8fcb-c85c55100f4e.png">

Latest official release 2.001

**Comment by xipmix** [comment]
This might be fixable in a similar way to volumio/Volumio2#1099 .

**Comment by xipmix** [comment]
This page https://www.musicpd.org/doc/user/config_audio_outputs.html explains the formatting that code is parsing. It seems likely that change will fix this issue too. I don't have any .m4a files to test with.

**Comment by marco-o** [comment]
Added a fix + pull request
