### ISSUE TITLE
Volume controls do not respond to multiple commands

### ISSUE THREAD

**Issue by Jotam** [volumio/Volumio2-UI#239]
I've had this problem since I started using Volumio. Whenever I use the volume controls, they will only respond once. When I click or tap them a second time, they don't respond at all. Hence, setting the volume in several steps is impossible. This happens in any browser I've tried (Firefox on Android, FF on Ubuntu, Chromium on Ubuntu, FF on Windows...) Any solution to this?

**Comment by Vigo0101** [comment]
Hello,
Same behaviour with v2.041 / RPi3 / official RPi Touchscreen.
Lets say volume is set to 50.
First touch on "volume +" increases volume to 60 (default stepping is 10)
Further touches on "volume +" do nothing.
Now, touch "volume -". Volume decreases to 40 and not 50 (60 - 10) as it should be.
Further touches on "volume -" do nothing.

**Comment by Jotam** [comment]
@Vigo0101 : Thanks for the additional description. What you describe is exactly what I experience.
