### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by bomek** [volumio/Volumio2-UI#247]
Hello, when i connect to the volumio UI from a computer with only an ipv6 address, socket.io is using the ipv4 address instead of the address/dns used to access the server.

GET http://1.1.1.1/socket.io/?EIO=3&transport=polling&t=LYsGMt7 net::ERR_ADDRESS_UNREACHABLE

**Comment by volumio** [comment]
We use only ipv4 with Volumio

**Comment by egeu5** [comment]
Why is this closed? In the year 2018 IPv6 ist 19 years old and should working like a charme! Almost every software supports it... for me it is not a feature request - it should be working from default. We are out of IPv4 space.

**Comment by ServerCare** [comment]
I wanted to use volumio over 4G... unfortunately there's only IPV6. The year is 2023, still no IPV6 on Volumio? Or did I miss something? ifconfig only shows me ipv4 :-(
