### ISSUE TITLE
optimizing ui for large libraries

### ISSUE THREAD

**Issue by joehajek** [volumio/Volumio2-UI#252]
Hello
I am new into github and volumio.  
I encountered the following problem with big libraries (i have 60k) songs.
The ui does only display one big list of artists/albums and it gets extremely slow when displaying the list (imesponse time > 10 secs). My proposed solution would be to split it up on different pages for all artists/albums starting with the same letter. In the settings for the ui there could be a select box to indicate the number of results  where  the splitting up starts. For example 500. If there are less than 500 artists the ui would look like it is now. If there are more you have seperate pages. Is there anybody  working on such a solution?  Have other people interest in this one? I will have to do it anyway because currently it is not usable for me because to slow. If you would want such a thing i will try my best to integrate otherwise i do a quick hack for myself
Regards joe

**Comment by marteadrian** [comment]
@joehajek : Same here. Did you already start with it? I'm also thinking to implement a paginator, or a grouping by first letter, as you already suggested.

**Comment by joehajek** [comment]
Hi
I have already finished. Works good
If you want the code i send it to you
Greetings
Am 13.03.2017 17:01 schrieb "marteadrian" <notifications@github.com>:

**Comment by marteadrian** [comment]
hi @joehajek - nice! It would be great if you can send me the code! do you have made a fork or do you have any link where I can merge from?

**Comment by joehajek** [comment]
Hi
No i didnt make a fork. And check it in because there where some permission
problems. I wrote the guys from volumio but didnt get a reply.  But there
are only two files involved in the mpd package serverside. And one on the
ui but that is in fact not necessary only hyperlinks and headings.
May be i can send you today evening otherwise Wednesday or Thursday.
Greetings
Am 13.03.2017 17:23 schrieb "marteadrian" <notifications@github.com>:

**Comment by marteadrian** [comment]
@joehajek : Ok, again, thanks a lot. So you'll send it here as a comment?

**Comment by joehajek** [comment]
Hi,

I wasnt able to upload the code - so here is a dropbox link.
https://www.dropbox.com/s/v71iy7mynma6oca/volumio_changes_joe.zip?dl=0

The code works fine for me.

=======================
Features in MPD Package
=======================
.) Possibility to split up Artist/Genres/Albums by starting letter (A-Z
lists).
configurable in config.json
.) Possibility to ignore leading article in band/album names (The beatles
will show up
under letter B) configurable in config.json
.) Possibility to optionally sort the results from the mpd server
configurable in config.json
.) Skipping of tracks that are more than one time in db
.) Artist and Genres skip if Artist/Genre has eg only one entry in whole
db  configurable in config.json

BUGFIXES:
.) search - only one artist was returned
.) lookup for album/artist takes albumartist not artist (otherwise all
samplers are split up in different albums)
.) display of albums of one band - the lookup was only for album name ->
all greates hits albums where always displayed
.) back button sometimes wrong

CHANGES:
.) Some places where the same statements where code twice, i tried to unify
in functions

=============
Features in UI
==============
.) artist and albums are hyperlinked so you can switch between views
.) seperate title of what is currently viewed (Album Name, Artist Name etc)
.) In Album/artist/Genre View there is also the hamburger menu to start
playback
( hamburger is not properly positioned)

Sometimes when you start up volumio and chose a track the system crashes,
but i think
it was already in the original code and i suppose it has to do something
with the tags of my mp3s.


If you have any questions or problems (or maybe ideas ;-) feel free to ask.
I would be glad if it finds the way into the git repository because than
keeping
up with the code would be easy. somehow i didnt manage it. sorry


greetings joe

2017-03-13 17:31 GMT+01:00 marteadrian <notifications@github.com>:

**Comment by kurtommy** [comment]
Hi @joehajek we have to find a solution to handle long lists! 
Try to submit a PR and we can take a look at your changes!

**Comment by joehajek** [comment]
Ah yes... i think the server part works without the ui part but not the
other way.
Greetings
Am 13.03.2017 22:17 schrieb "joe hajek" <joe@blackbox.net>:

**Comment by volumio** [comment]
Hi @joehajek ! This looks really interesting! 
Could you please send us two PRs (one for UI and one for backend?) this way we can look at them and merge... Thank you!

**Comment by joehajek** [comment]
If you tell me what is a pr then i will try ;-).
Sorry i never used git before and i was only able to check out not to check
in.

Joe
Am 13.03.2017 22:28 schrieb "Volumio" <notifications@github.com>:

**Comment by volumio** [comment]
Here is a little guide: 
https://help.github.com/articles/creating-a-pull-request/

Let me know if you need more help!

**Comment by joehajek** [comment]
Ok i will give it a try but i am home not before end of the week.
Greetings
Am 13.03.2017 22:53 schrieb "Volumio" <notifications@github.com>:

**Comment by joehajek** [comment]
hi
i made a pr for the server side changes of the mpd package. when i wanted to do the same in the Volumio2-UI repository it didnt work and said no permission. sorry dont know what the problem is. i used git desktop for windows
greetings

**Comment by volumio** [comment]
Hi Joe, didn't get your PR.Where did you send it? 
for the Volumio 2 UI, I don't understand what the problem is... sorry

**Comment by joehajek** [comment]
did you get it now ?

**Comment by augustsix** [comment]
I would love to see this implemented as a feature. The files don't seem to be compatible with the new UI.
