### ISSUE TITLE
hidden box

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#26]
when selecting a song a the bottom of the list, selection box is hidden (right bottom corner)
![hiden-window](https://cloud.githubusercontent.com/assets/12850139/12589293/468cdc24-c45d-11e5-80ef-90a473768591.png)

**Comment by kurtommy** [comment]
This is not a bug, you have space for scroll the list as you can see from the scroll bar. The selection box will open up when you can't scroll more.
