### ISSUE TITLE
Provide additional information that is helpful to reproduce a build

### ISSUE THREAD

**Issue by earlchew** [volumio/Volumio2-UI#264]
For a given release, I want to reproduce the build so that I can confidently patch or improve the operation of that release.

To improve the situation, I would suggest:
* Including the SHA1 of the Build repository in the release image (eg include the SHA1 in /etc/motd)
* Add the SHA1 of the source branch to the metadata when creating the subtree split in the Volumio2-UI repository (eg perhaps the `--annotate` option would be suitable)

Additionally, I suspect the documentation in the Volumio2-UI README.md is slightly incorrect:

    diff --git a/README.md b/README.md
    index 032ebce..40496c6 100644
    --- a/README.md
    +++ b/README.md
    @@ -19,7 +19,7 @@ Only the `dist/` directory is needed by Volumio2, so there is a [dist branch](ht
     To update the dist branch with the latest changes, run:

     ```shell
    -git subtree split --prefix dist -b dist
    +git subtree split --prefix src -b dist
     git push origin dist:dist
     ```

There are three git repositories involved in a build:
* https://github.com/volumio/Build
* https://github.com/volumio/Volumio2-UI
* https://github.com/volumio/Volumio2

Once I installed a release, I was not able to find determine the git SHA1 of the Build repository used to construct that build.

The .git/ directories are available in the release image, and can be queried for their git SHA1 values. For example, querying in /volumio shows:
```
commit 4bc5ff365b624e5e7bf11a639fb554ff0ec830bd
Author: volumio <info@volumio.org>
Date:   Mon Dec 12 00:02:13 2016 +0000

    partial fix of multiroom selector
```
This uniquely identifies the commit used in the Volumio2 repository.

The corresponding query in /volumio/http/www is less useful:
```
commit 2917c90455f71218a533547d052fea30f4ade08e
Author: Volumio <info@volumio.org>
Date:   Mon Dec 5 16:56:49 2016 +0000

    Deploy to Dist Branch
```
This uniquely identifies the commit within the pruned dist/ branch in the Volumio2-UI repository, but does not provide enough information to resolve this back to the master/ branch in the repository.

**Comment by volumio** [comment]
Sensible... I will add it !

**Comment by volumio** [comment]
Done
