### ISSUE TITLE
Provide a more polished page title than {{pageTitle}}

### ISSUE THREAD

**Issue by earlchew** [volumio/Volumio2-UI#265]
When I open my browser to access the volumio player, I want to see a more attractive page title than `{{pageTitle}}`, so that the application looks more like a polished product.

I can see `{{pageTitle}}` in `index.html` but I'm not quite sure what the appropriate mechanism is to address this.
* Should `{{pageTitle}}` be replaced by the static text `Volumio`?
* Should `{{pageTitle}}` be replaced by the hostname?

**Comment by volumio** [comment]
It is a dynamic value: {{pageTitle}} will become Volumio or the song title after some milliseconds that the page has loaded... In some cases it might take more, but I don't see it as a dealbreaker. We'll see what we can do here

**Comment by volumio** [comment]
Fixed
