### ISSUE TITLE
playing the result of search

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#28]
The result of research cannot be played : nothing happen

**Comment by volumio** [comment]
Mmmm... it works for me...

**Comment by balbuze** [comment]
I re did the test and I confirm that on my two systems, the result of the search cannot be play by selecting "play" or adding to playlist.
edit : after a reboot it works.... seems there is a case in which the problem occurs. I 'll dig in it.

**Comment by volumio** [comment]
Thanks!

**Comment by balbuze** [comment]
I think I get it!
1 refresh the window of your browser
2 go to the browse page and search something
3 in the result selecting one to be played : nothing
4 clic on the house
5 clic on music library
6 search
7 in the result select one to be played : it works !
Unfortunatly when it does not work , nothing happen the log file...

**Comment by balbuze** [comment]
work now, I close it
