### ISSUE TITLE
Missing assets: volumio-bg.jpg, thumb-volumio-bg.jpg since update to 2.114

### ISSUE THREAD

**Issue by gonace** [volumio/Volumio2-UI#294]
Since updating to 2.114 these assets can't be found, the file can't be find on the file system. Is this an update issue?

Regards

**Comment by xipmix** [comment]
Seems they were removed here: c66ac17b9be286954cc281b289dc0031adcab658
Why is this a problem? As far as I can see they weren't being used by the UI code for some time before that commit.

**Comment by gonace** [comment]
These assets are being used under "Appearance", I get a HTTP 404 request for that image, and on every page that the default background is being used.

**Comment by xipmix** [comment]
Thanks for that, I will have a bit of a rummage around.

**Comment by xipmix** [comment]
Struggling to understand this. The appearance plugin just iterates over the contents of the /data/backgrounds directory. So it should not start from that and not know about files not in that directory.

Could you please post:
 * your system version (Cog menu -> System), if it is not 2.114.
 * if possible, the output from:
```
$ ls -l /data/backgrounds
$ cat /data/configuration/miscellanea/appearance/config.json
```
To do the latter you will have to ssh in to your volumio and type the commands.

How are you noticing the 404? As a 'missing' image icon in the browser or as a log file entry? If so, which log please?

**Comment by xipmix** [comment]
This may have been caused by a different commit that what I thought, see volumio/Volumio2#1084 .
Note that the thumbnail version is auto-generated from the larger one.

**Comment by volumio** [comment]
Fixed
