### ISSUE TITLE
Manual Plugin install: happens twice

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2-UI#295]
Sorry for cross-posting, but it very much seems the root cause of duplicated manual plugin download&install pertains to this part of the code (page reload? or something).
More here: https://github.com/volumio/Volumio2/issues/847
This is a longstanding issue which seems to still be here with 2.114 build

**Comment by macmpi** [comment]
The issue still exists: by closing here, do you think the root cause is in [Volumio2 side](https://github.com/volumio/Volumio2/issues/847) rather than in Volumio2-UI here?
It seems like a UI refresh triggering a second download after 1 minute or sth.

**Comment by volumio** [comment]
Sorry did not notice that. 
@kurtommy what do you think?

**Comment by macmpi** [comment]
Since drag-&-drop remains so much of an issue, whose cause is hard to nail-down, how about replacing this by a more "classical" file upload button so that user can pick & select file through client's own file explorer?
More old-fashioned, but maybe more robust for now, as currently this makes 3rd Party plugins install really an issue (some authors are up-to [protecting against duplicate installs](https://github.com/Saiyato/volumio-kodi-plugin/blob/master/install.sh#L5) within their install scripts!).

**Comment by ashthespy** [comment]
Any updates on this? Just had this happen on `v2.246`

**Comment by macmpi** [comment]
Still open in https://github.com/volumio/Volumio2/issues/847 which has more details.

Wondering if duplicate download (and follow-up install) is not due to browser's default action supplementing drop zone definition, as suggested [here](https://github.com/blueimp/jQuery-File-Upload/wiki/Drop-zone-effects):
`Note that preventing the default action for both the "drop" and "dragover" events is required to disable the default browser drop action.`
