### ISSUE TITLE
My Music panel: show/manage USB disks

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2-UI#302]
Would be nice if mounted USB disk could show up in a similar section as Network drives one.
It would then make sense to add a unmount/mount button for such drives, so that disks could be safely unmounted before pulling them out of USB socket...

While at it, adding a such mount/unmount button to Network drives could make sense too: sometimes a previously registered Network Disk may appear on the network well after Volumio is started (i.e. shared directory of a laptop that it powered-up later).

**Comment by xipmix** [comment]
In the network disk case, at bootup volumio tries 5 times to mount the disks known in the configuration, but it only waits about 5sec each time. So indeed it would be nice to have a 'retry mount' type of function in the UI. It seems like it would be simple to make the tick/cross mark clickable, to retry that particular mount.

**Comment by xipmix** [comment]
How do you envisage the usb case working - list all devices on the system? Would you exclude the 'onboard' devices?

**Comment by macmpi** [comment]
For USB disks, the principal interest is to unount really, as disks do mount by default upon insertion. Unmounting properly before user removes a USB disk is highly desirable to avoid potential data corruption.
(of course if disk is unmounted but not yet removed, user could still appreciate to have a possible mount action, but this is really secondary I guess, as user may equally remove/re-insert).

**Comment by macmpi** [comment]
Thinking of which..., USB unmount would be [nice for CDs also](https://volumio.org/forum/support-for-usb-player-t5862.html#p28754)  :)
