### ISSUE TITLE
Small screen: clear queue is not accessible

### ISSUE THREAD

**Issue by biva** [volumio/Volumio2-UI#304]
On small screen (4" WVGA 480 x 800), I can't clear the queue: the Trash icon is below and grey, while it's working on bigger screens (Chrome on Android 4.3 / Volumio 2.118):

![screenshot_2017-03-17-13-16-32](https://cloud.githubusercontent.com/assets/9964305/24042986/b735ef70-0b14-11e7-9935-ec862f9e1beb.png)

**Comment by xipmix** [comment]
I assume you tried this ... what happens if you turn the phone through 90 degrees?

**Comment by biva** [comment]
@xipmix I didn't try it before your suggestion :( But you're right, that's a good workaround.

Do we want to keep this issue open (the issue is real), or it's not a priority (I would close it in this case)?

**Comment by xipmix** [comment]
Leaving open or not is up to you and volumio.
If you feel it matters enough, leave it open.

The only way I can see to fix it is for the code to detect the
overflow and resize the icons so they fit, or use small alt text
in place of icons. I am not sure this is possible.

**Comment by biva** [comment]
@volumio I let you decide if it's worth improving the behavior for small screens, or if we close this issue
