### ISSUE TITLE
strange accented caracters

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#31]
Some accented caracters display is wrong "é" "è" "ê"
![caracters](https://cloud.githubusercontent.com/assets/12850139/12626425/e0d8f85e-c538-11e5-9a77-fbc8b1f79274.png)

**Comment by volumio** [comment]
Thanks, we'll send in utf 8

**Comment by mpasteur** [comment]
for info i don't have any problem with accents. @balbuze is it a cifs or an nfs share ?

**Comment by balbuze** [comment]
hi,
I have found the problem and Volumio is not involved ! My files are named correctly, but if I look at the tag inside, the wrong caracter is here ! I can't remember how it was ripped it...
Sorry for this bad analysis.
