### ISSUE TITLE
Locale/Regional settings UI

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2-UI#317]
Just referring [this](https://github.com/volumio/Volumio2/issues/1082#issuecomment-287994647) here as it is essencially UI related:
Would probably make sense to complete and group all Locale/Regional related stuff within UI:
- language (already exists in Appearance)
- wifi [CRDA](https://github.com/volumio/Volumio2/issues/1082) with [proper county code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes) `REGDOMAIN=xx` in `/etc/default/crda`
- [Timezone](https://github.com/volumio/Volumio2/issues/741#issuecomment-256066520) with `timedatectl`
- [keyboard](https://volumio.org/forum/installing-the-touch-display-plugin-t6032-20.html#p29849) (issue for chromium-based plugins for instance) & [system's locales](https://github.com/volumio/Build/pull/97) with `localectl`
- ...

**Comment by RD07a** [comment]
As the language config is already implemented as a dynamic UI setting and the keyboard topic is rather irrelevant for a normal WebUI user I would recommend to consider implementing the rather important "one time" settings of the [WiFi CRDA](https://github.com/volumio/Volumio2/issues/1082) and [timezone ](https://github.com/volumio/Volumio2/issues/741#issuecomment-256066520) into the **First Config Wizard**.

Especially the WiFi CRDA problem could completely block the usage of Volumio via WiFi for some users as their home WiFi may not appear in the available networks list.
