### ISSUE TITLE
search tool

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#32]
Sometime it works well and rather fast and sometime it is very slow : the browser ask to interrupt the script several time. I can't see the difference between the occurrence... I'll try to undesrtand...

**Comment by volumio** [comment]
. K
Il 27/gen/2016 09:18 PM, balbuze <notifications@github.com> ha scritto:Sometime it works well and rather fast and sometime it is very slow : the browser ask to interrupt the script several time I can't see the difference between the occurrence I'll try to undesrtand
