### ISSUE TITLE
share size differs between cifs and nfs

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#33]
I mount the folder twice : 
using cifs
using nfs
The size displayed differs in webUI
In the console you can see that it contains the same things.
Have you noticed the same ?
![share-size](https://cloud.githubusercontent.com/assets/12850139/12627425/0a82f9b6-c53e-11e5-97a2-bfe960aeb83c.png)

**Comment by volumio** [comment]
Not much to do here...
