### ISSUE TITLE
Integration of track#, disc# in interface

### ISSUE THREAD

**Issue by pwnagepeter** [volumio/Volumio2-UI#335]
How about adding the track# and disc# to all instances where tracks are listed?

Currently come to mind:
1.) track-info-bar
2.) browser
3.) queue

When handling multi-disc albums it makes sense if only one disc should be identified and added to queue/playlist.

**Comment by Awazleon** [comment]
Hello,

I would like toalso push that request.
Using multi-CD records, it would be fine to add the disc# (ID3 Tag TPOS    [#TPOS Part of a set]) when browsing the album. Something like : 
Disc 1
01 - Track title
02 - Track title
.
.
Disc 2
01- Track title
etc...
