### ISSUE TITLE
Fast forwarding using the timeknob

### ISSUE THREAD

**Issue by Nielske62** [volumio/Volumio2-UI#338]
I have a problem when using the timeknob which displays the minutes:seconds of the song. Whenever I click on the circle surrounding this information to fast forward in the song it skyrockets to a huge number and the fast forwarding circle is bugged and therefore useless. This also stays when I skip the song, but goes away when a select a new song to play. Does anyone have an idea on how to fix this?

![problem_github](https://cloud.githubusercontent.com/assets/16865993/25965152/6fa8b298-3687-11e7-96d9-163d6b5ba9cc.png)

**Comment by volumio** [comment]
Fixed, it was a spotify plugin issue
