### ISSUE TITLE
result of search tool

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#34]
The search tool does not return the content of a cue file

**Comment by balbuze** [comment]
Some file with no metadata (flac files don't know for others) appears as a empty line as result of search.If selected and played, the full path appears in the playback window.
 By going " by hand" at the same place the name of file appears correctly

**Comment by volumio** [comment]
As for .cue, adding the show would bringe a massive performance handicap, while for file names this makes total sense, I'll add it!
