### ISSUE TITLE
Volumio Menu App

### ISSUE THREAD

**Issue by yfr** [volumio/Volumio2-UI#340]
@volumio i just did a quick setup of an electron app that works from the menu bar https://github.com/yfr/volumio-menu

Hope you like it. 

![screenshot](https://cloud.githubusercontent.com/assets/1379306/26284948/542ed9ae-3e46-11e7-9aa1-fe505964dca5.png)

**Comment by volumio** [comment]
Yes I do! 
Are you experienced in electron apps? If yes it would be nice to do some stuff I've been thinking for a while... Could you please contact me at info at volumio dot org?

As soon as I get to my mac I will try it!

**Comment by yfr** [comment]
I did some playing around with electron apps. But I like to do more.

The current state of the app is very basic and I too have more ideas for this.
