### ISSUE TITLE
search tool result suggestion 

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#35]
I think it could be convenient in the result of a search to have a "go to artist" or "go to album" or "display this artist" or something like that

**Comment by volumio** [comment]
Yes, good idea, I'll look into this

**Comment by apinner** [comment]
As was suggested quite a while ago on the forums; https://volumio.org/forum/search-for-album-and-artist-results-t544.html

**Comment by balbuze** [comment]
It is implemented yet! Dev branch & last Ui

**Comment by apinner** [comment]
Ah awesome so we can close this one? I have not done a pull in a while to check out the latest changes.

**Comment by balbuze** [comment]
For me it's OK. You have tree small dot near favourite and when you click a small window allow to go to artist or album

**Comment by apinner** [comment]
Oh this is on the playback window? I have seen that. 

Wasn't the suggestion for the search results?
