### ISSUE TITLE
improve readability

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#36]
In the browse tab or queue tab, the contrast between the artist/ album and the background is not important enough : it is difficultly readable on smartphone (with standard screen) when the sun shine...
Maybe a other choice of color to improve readability could be something to consider.
something like the picture (this just a suggestion) is more readble 
![contrast](https://cloud.githubusercontent.com/assets/12850139/12866144/376b4366-ccc3-11e5-8d88-94af30d79b86.png)

**Comment by volumio** [comment]
Agree, we'll change this!

**Comment by balbuze** [comment]
it's more readable now !
