### ISSUE TITLE
UI test and issues

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#38]
with the last commit 159b3138b86b08ff8cebf580a2da92bca8b105a7 there is a problem with the configuration menu : it is hidden by some element and can't be selected
![hidden menu](https://cloud.githubusercontent.com/assets/12850139/13085774/2e9faa40-d4e0-11e5-8004-fa8f1e7fec15.png)
edit : not only the right menu, the play back next button as well
![hidden-m2](https://cloud.githubusercontent.com/assets/12850139/13085873/a5b38b10-d4e0-11e5-8d95-31c63fd6d8d7.png)

**Comment by volumio** [comment]
Yep we're aware of the issues and working to solve them... 
It would be great if you could make up a list of issues so we can have them all in case we miss some..

thanks

**Comment by balbuze** [comment]
Ok I start a list here, that can be completed by anyone finding something wrong. Or if you want it to be different, let me know. I'll add element if I find problem
**Desktop UI**
1 -overlap problem (see above) with menu, playback command, multiroom frame
**Mobile UI**
1- not a bug just advice : playback command are placed a the bottom and browse/playback/queue at the top. Why ? it was coherent with desktop UI.
2- overlap problem (see above) with menu, playback command, multiroom frame
3- Volume slider inverted : going down when moving up and vice versa

**Comment by balbuze** [comment]
overlap problem (related above)
![screenshot_2016-02-17-20-48-09](https://cloud.githubusercontent.com/assets/12850139/13122858/678de6b2-d5b9-11e5-99b8-a5c05e23b49a.png)

**Comment by apinner** [comment]
I'll tag on here rather than start a new issue.

Its very easy to confuse the volume control. Clicking the decrease and increase icons quickly can cause it just jump back and forth. When it jumps, it loses 1 so you end up with 29, 39, 49 etc. If you set it to zero again it will do 0, 10 , 20, 30... until it jumps again and it will jump back to 29.

The icons are not central in the boxes beneath the dials.

Purely for look

`#playerButtons .playPause {
    border: solid 3px #54c698;
    height: 60px;
    width: 60px;
`
looks a bit nicer to my eye.

**Comment by apinner** [comment]
> 1- not a bug just advice : playback command are placed a the bottom and browse/playback/queue at the top. Why ? it was coherent with desktop UI.

I believe that decision was made for usability. It puts the controls closer to your thumb on larger phones. The reason why just about every other music playing app does the same thing.

**Comment by balbuze** [comment]
update list of issues (post 3)

**Comment by apinner** [comment]
A couple more that i have come across. 

1. When using a mouse scroll wheel on the volume knob, the position changes but the numbers do not.

2. When you turn repeat and shuffle on the icons do not remain green.

3. Mute doesn't seem to change anything in the UI.

**Comment by balbuze** [comment]
update list of issues (post 3)
add screenshot of point 12 below
![screenshot_2016-02-21-18-24-16](https://cloud.githubusercontent.com/assets/12850139/13204220/c9fd6fd4-d8ca-11e5-9799-bc1009b093ff.png)

**Comment by balbuze** [comment]
It become better and nicer nearly hours after hours ! And I want to congratulate this amazing work !

**Comment by apinner** [comment]
nice to see you trying out my branch!

I need to fix that play button issue.. my fix for the opacity doesn't work when it shifts to the bottom. :/

That long name issue is a difficult one as i think thats going to always be a problem. I wonder if we need to do something like `text-overflow: ellipsis;` for when titles get over a certain length?

**Comment by balbuze** [comment]
Yes, there small adjustement... But already very promising. For the long text maybe what your are saying ( but I don't know), or maybe a way is to display only the beginning, let's say the first 2 lines or a fixed number of characters.

**Comment by balbuze** [comment]
update post 3 with commit 6c43df71c81b0ed0fef997dea2f35c60c3163149

**Comment by balbuze** [comment]
update post3 with commit b27ee08d08e7c8d0f65148ae2d311dd516a890d4 and update 0.843
