### ISSUE TITLE
Interrupted requests / flashing page on Mini86 version

### ISSUE THREAD

**Issue by mjtorn** [volumio/Volumio2-UI#385]
This happens both on the local Chromium (HDMI) and remote Firefox.

The browser keeps making XHR POSTs and WS and XHR GETs, with this in the output.

> Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=Tq3iXeYnXMyUC8rHAAQI.  vendor-5984c6714f.js:202:24493
> The connection to ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=Tq3iXeYnXMyUC8rHAAQI was interrupted while the page was loading.  vendor-5984c6714f.js:202:24493
> Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=ofyCicwO3XBcbeMrAAQJ.  vendor-5984c6714f.js:202:24493
> Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=HDwKt4TeITSmGTJDAAQK.

I have not seen the page work on Firefox, but it does work occasionally on the local Chromium browser.

The WS GET is like http://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=jnVRXYZUoEJbQX2-AAQQ

The XHR GET is like http://192.168.1.3/socket.io/?EIO=3&transport=polling&t=LufhDvo&sid=QBZrnVLJ_R__g62vAAQ2

Edit: Response looks like `97:0{"sid":"KQemUjQn3cm725NrAATh","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}2:40`

The XHR POST is like http://192.168.1.3/socket.io/?EIO=3&transport=polling&t=LufhniG&sid=loOXNzM2zQ1-XgcgAARl

with the content

`27:424531["getTrackInfo",null]22:424532["getSeek",null]27:424533["getMenuItems",null]34:424534["getMultiRoomDevices",null]27:424535["getMultiroom",null]27:424536["listPlaylist",null]`

Edit: it returns `ok`

Nothing looks obviously out of whack, but still the UI doesn't stabilize.

**Comment by mjtorn** [comment]
```
volumio@volumio:/volumio$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
VOLUMIO_BUILD_VERSION="4d5085633727854366f9632337ac84f802a29916"
VOLUMIO_FE_VERSION="35c935291e7fc0c1a3a0465e86e08f0e2d8b9bf1"
VOLUMIO_BE_VERSION="03ddbcecd350a717be3ad92051009d820fe70bd0"
VOLUMIO_ARCH="x86"
VOLUMIO_VARIANT="volumio"
VOLUMIO_TEST="FALSE"
VOLUMIO_BUILD_DATE="Mon Aug  7 17:35:03 CEST 2017"

VOLUMIO_VERSION="2.254"
VOLUMIO_HARDWARE="x86"
```

**Comment by mjtorn** [comment]
Out of some strange desperation, I even tried this:

> volumio@volumio:/volumio/http/www$ git show origin/dist
> commit 78eb4c86ea41779e109a1b210b0d6623f8e1a859

> volumio@volumio:/volumio/http/www$ git reset origin/dist --hard
> HEAD is now at 78eb4c8 Deploy to Dist Branch

Did not help, but I didn't really think it would.

**Comment by mjtorn** [comment]
I did a factory reset, and without configuring anything but the IP address, performed the system upgrades. There were no problems. I have a NAS configured, and listen through USB.

Does this give any insight?

**Comment by volumio** [comment]
My guess is that you had the old UI in your browser cache... Did you experience the problem again since then?

**Comment by mjtorn** [comment]
I did clear the browser cache, so that is a weird cause, but otherwise it would make sense!

I use wireless.

And everything did work out eventually after a factory reset and re-upgrading. Works like a charm, really.

If there's any more information I can give, I'm happy to, but I don't know what I could find after the factory reset anymore. So feel free to close the issue if there's nothing I can help with.

Thanks!

**Comment by volumio** [comment]
It would be really useful if you could give me any information about this issue, as much as you can... Since this is something that I would like to understand as it might happen in other cases

**Comment by mjtorn** [comment]
Hmm, I'm trying to think of what else... Wireless, uses Samba to mount from NAS, got the factory-preinstalled Mini86, did the rounds of upgrades, cleared the cache... Occasionally hooked to the TV over HDMI, uses USB to connect to a Hegel H160...

If I still had the broken setup, I could theoretically do some forensics, but I love my music player too much to have it broken.

**Comment by volumio** [comment]
And I can't blame you... Any particular setting you've set before it broke?

**Comment by mjtorn** [comment]
I enabled SSH, and I may have clicked the test mode back and forth, but certainly left it off, as I prefer my software stable (most of the time). Is there a chance I might have forgot testing on and got a dud beta version?

IMO that /DEV/ view could be a bit more verbose as to what's actually turned on and not at the moment...

**Comment by mjtorn** [comment]
Now it started doing this again, for no obvious reason. Rebooted the box, and cleared my browser cache and the cookie for it, without help.

```
Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=LzJlc_AWaJqq_HE9AAAi.  vendor-5984c6714f.js:202:24493
[TEME]: volumio [VARIANT]: volumio  app-94af8e6c77.js:3:6497
IP from API Object { data: Object, status: 200, headers: Ae/<(), config: Object, statusText: "OK" }  app-94af8e6c77.js:3:7212
false  app-94af8e6c77.js:4:30125
playerService.volume 0  app-94af8e6c77.js:4:27160
Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=Xjta9Ns3O03ZfkknAD-S.  vendor-5984c6714f.js:202:24493
Firefox can’t establish a connection to the server at ws://192.168.1.3/socket.io/?EIO=3&transport=websocket&sid=fEJZ7BPWBuZDClDtAD-T.  vendor-5984c6714f.js:202:24493
```

**Comment by mjtorn** [comment]
Not sure if related, but I could never `Remove` songs from the queue in /DEV/.

**Comment by mjtorn** [comment]
I can use an external MPC client to play music, so that's not affected.

**Comment by volumio** [comment]
Could you please:
- Tell us what you did before the problem occured.
- If you're using a ad blocker, please disable it
- Is 192.168.1.3 the right IP address of your PI?
- Can you send us a bug report via /DEV page (put mjtorn as motivation)

**Comment by mjtorn** [comment]
I was doing nothing, listening to vinyl LPs and filling in some bureaucracy online. Decided to listen to something that doesn't require constant intervention, changed to the tab, and it was flickering again.

I do not have an adblocker on this machine. No addons of any kind.

The address is correct.

The log looks like it can be made public http://logs.volumio.org/volumio/GlAFYBg.html

**Comment by volumio** [comment]
Language?

**Comment by volumio** [comment]
Can you see the volumio Hotspot?

**Comment by mjtorn** [comment]
The language is English and I'm sure I turned off the hotspot. Not really sure why I'd want to have an extra hotspot.

The IP is configured manually. For some reason once my ZyXel ADSL Wifi modem gave it an arbitrary ID, and I set the static DHCP straight, the ZyXel kept giving the wrong IP. That's why I use manual config for the IP. Maybe the leases are out and the ZyXel would do the right thing, but I can't be arsed to find out as long as the Volumio's properly online with the correct IP.

**Comment by mjtorn** [comment]
```{"status":"play","position":0,"title":"the cry of morgoth","artist":"m²","album":"war of sound","albumart":"/albumart?cacheid=0&web=m%C2%B2/war%20of%20sound/extralarge&path=%2FNAS%2FMusic%2Fm%C2%B2%20-%20war%20of%20sound&metadata=false","uri":"mnt/NAS/Music/m² - war of sound/ant-zen - war of sound - 01 the cry of morgoth.flac","trackType":"flac","seek":26289,"duration":230,"samplerate":"44.1 KHz","bitdepth":"16 bit","channels":2,"random":null,"repeat":null,"repeatSingle":false,"consume":false,"volume":100,"mute":false,"stream":"flac","updatedb":false,"volatile":false,"service":"mpd"}```

I noticed the `seek` keeps going up in the /DEV/ view.

```{"status":"play","position":0,"title":"the cry of morgoth","artist":"m²","album":"war of sound","albumart":"/albumart?cacheid=0&web=m%C2%B2/war%20of%20sound/extralarge&path=%2FNAS%2FMusic%2Fm%C2%B2%20-%20war%20of%20sound&metadata=false","uri":"mnt/NAS/Music/m² - war of sound/ant-zen - war of sound - 01 the cry of morgoth.flac","trackType":"flac","seek":295842,"duration":230,"samplerate":"44.1 KHz","bitdepth":"16 bit","channels":2,"random":null,"repeat":null,"repeatSingle":false,"consume":false,"volume":100,"mute":false,"stream":"flac","updatedb":false,"volatile":false,"service":"mpd"}```

Not sure what the unit should be, but it's getting pretty big.

And Volumio is not on play.

Not sure if related to the UI problems.

**Comment by volumio** [comment]
I thinked I fixed it... It was a misalignment between socket.io libraries in front end and backend... 
Could you please help us test if the issue is actually solved? 
To do so you can:
- Update all the way up to  2.264, and refresh your browser

OR 

- Flash the 2.264 ,  you can find it here:
http://updates.volumio.org/x86/volumio/2.263/volumio-2.263-2017-09-06-x86.img.zip

Please let me know

**Comment by mjtorn** [comment]
Glad to hear this!

With the UI flashing and no way to upgrade through the /DEV/ page, I need to take a longer moment later to do the factory reset and/or make that USB stick. Hopefully I'll have time today, and good news later in the day...

Is there a CLI method?

Thanks!

PS.
Would be nice to see the current version and be able to check for updates in /DEV/ in case of emergency ;)

**Comment by mjtorn** [comment]
Put that on a USB stick, and it _kinda_ works. I mean, the UI doesn't blink and it reports being the expected version, but there's no option to install that on the machine. Maybe I'm missing something on the new grub menu, maybe I can hack it somehow to get the software onto the hard drive, but it looks like we're going in the right direction!

**Comment by volumio** [comment]
Yes there is no option to install it. If you can, please just test it like this, and as soon as we find out that this issue is solved I will release an update so you won't have to reflash.

Thank you very much for your help

**Comment by mjtorn** [comment]
I'll use it a while and report back when I can, hopefully soon.

Installing on the HDD would be great, because with the flashing UI, I can't do an OTA update. Or is there a CLI method?

Thanks!

**Comment by volumio** [comment]
There are several ways you can do an OTA update. First one is do a factory reset then update.
To do a factory reset, just place on a USB drive (FAT32) a file called factory_reset 

If that does not work I will help you

**Comment by mjtorn** [comment]
Maybe I'm not focusing enough, but should the USB stick be otherwise empty? And then if the file is found, the PC will not only reset all user data, but also go to the network and pull in the latest version?

Because just resetting isn't going to cut it, that'll leave the UI unusable and blinking, so I can't click my way through.

**Comment by mjtorn** [comment]
Either way, I'll be gone for a while, so if there's any reason to push out an update, please feel free to do so. I'm quite sure I won't be able to do anything until mid next week.

Cheers!

**Comment by mjtorn** [comment]
Does this mean a release would be underway?

The PC release on the download page is still at 2.201 and I wouldn't mind doing the factory reset and upgrade :)

Thanks!
