### ISSUE TITLE
first test...

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#4]
I have just test the last build.
I know it is far from being finished, but I just want to report a strange behaviour, when I change something ( the volume or next song) on a device, lets say my computer, the page is not refreshed on a other device (my phone). And if I refresh, I get a "cannot get /playback". The only way is to remove "playback" from the address.

**Comment by volumio** [comment]
You're absolutely right! 
This problems are backend related, I've opened 2 issues for them
https://github.com/volumio/Volumio2/issues/87
https://github.com/volumio/Volumio2/issues/86

thanks!
