### ISSUE TITLE
Dynamic Favicon

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#41]
Is there an easy way to change the favicon depending on the player state?

I was thinking it would be nice to dynamically change the favicon to show if the player is in a play or pause state. Favicons attached.

![favicon-play](https://cloud.githubusercontent.com/assets/85802/13202898/4d55270c-d8a1-11e5-905c-c84349268b07.png)
![favicon-pause](https://cloud.githubusercontent.com/assets/85802/13202897/4d551154-d8a1-11e5-889b-8d61fa1fbed7.png)

**Comment by volumio** [comment]
That's a great idea! What do you think if we remove the line in the circle and just center the play and pause button inside it?

**Comment by apinner** [comment]
Like these?

![favicon](https://cloud.githubusercontent.com/assets/85802/13204900/05f0883e-d8d3-11e5-9229-cc3d9fbed224.png)
![favicon-muted](https://cloud.githubusercontent.com/assets/85802/13204902/05f11c4a-d8d3-11e5-9800-9384f2f47c09.png)
![favicon-pause](https://cloud.githubusercontent.com/assets/85802/13204901/05f149c2-d8d3-11e5-88ec-6a2ebb3033c7.png)
![favicon-play](https://cloud.githubusercontent.com/assets/85802/13204903/05f24a34-d8d3-11e5-9dc4-c718545faac7.png)

Feel free to use them.

**Comment by volumio** [comment]
Oh YES! Nice!

**Comment by volumio** [comment]
Done in latest merge!
