### ISSUE TITLE
Wireless doesn't work when wired network is unplugged if you set a static IP

### ISSUE THREAD

**Issue by omehegan** [volumio/Volumio2-UI#429]
It took me a couple of hours to figure this out! After flashing 2.296 on my Raspberry Pi and doing initial configuration via the wired network, I connected Volumio to my wifi network and gave it a static IP as usual (because Android doesn't support mDNS so I can't use http://volumio.local to access it from my phone). Then I powered down the Pi and moved it to where it normally lives, plugged into my stereo with wifi access... and I couldn't connect to it. I repeated this exercise several times before digging in a little more deeply. To make a long story short, if you set *either* network interface to have a static IP, the wireless interface will stop working when you unplug the wired network. I couldn't believe I was seeing this, but I confirmed it. Once I switched both interfaces to use DHCP, then when I unplugged the wired network I could still ping the wireless IP. I confirmed with ifconfig before and after this testing that I was in fact pinging the wlan0 IP address.

**Comment by xipmix** [comment]
Thanks for raising this. It should really be tracked as a backend issue, see cross-link above. Would you mind closing this one?
