### ISSUE TITLE
Browse Screen

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#45]
I did some work on the settings pages making them look like my mock ups on the development branch.

I've looked at doing the same on the browse page as per [this mock up](https://projects.invisionapp.com/d/main#/console/6145656/136991338/preview); but i keep breaking things. :/

Could you take a look @kurtommy?

**Comment by kurtommy** [comment]
@apinner Hi, I'm working now on voliumio theme. For the future you Must create a new branch from development, push that branch and make a PR for merge it with development. Don't work directly on development branch please.
