### ISSUE TITLE
Favorites for album and artist

### ISSUE THREAD

**Issue by jbonlinea** [volumio/Volumio2-UI#488]
Hi guys, 

I've been using Volumio for a little while now and appreciate it a little more every day, thank's for your comitment ! 

I however feel very frustrated not to be able to add albums or artiste to favorites.
Today I'm into a certain artist, or a certain album, and tomorow It'll be an other, thus it seems natural to me to pin them as my favorites :-)

I could create playlists, but I may be into an artist that I wand to access quickly, but also wish to listen a specific album of this artist today and an other tomorow, so I would have to creat a playlist for every albums I'm into at the moment... 
Not the most natural thinking, and not very handy ! 

So I belived having the ability to add artist or album to favorites would be a great feature ! 
The awesomennes would be to be able to add youtube search to favorites and spotify artist/album, for the plugins I uses

Cheers, and thank's again for your awesome work

**Comment by robcee** [comment]
+1 from me. I would love to see greater tagging and quick access options. In the Browse tab's "Home" screen, adding "Favourite Artists" and "Favourite Albums" categories would provide quick access without having to overpopulate the existing Favourites category.

On the filesystem side, having /data/favourites/artists and /data/favourites/albums would be good places to put them.
