### ISSUE TITLE
Note Specific Versions of NodeJs etc. required

### ISSUE THREAD

**Issue by tanabi** [volumio/Volumio2-UI#489]
Hey there;

As someone new to Volumio (and nodeJS in general to be honest) I went ahead and downloaded the latest and greatest of everything and got a weird error when trying to use gulp:

`
tore.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/xxx/work/Volumio2-UI/node_modules/karma/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/work/Volumio2-UI/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:662:30)
`

Doing some research, this is because I had installed node 9.7.1 but Volumio needs node 6.11.0.  This should be documented clearly, or better yet update the software to work with newer node :)

**Comment by tanabi** [comment]
The easiest way to develop (if anyone comes across this breadcrumb) is to use the x86 vm with your virtualizer of choice (I used virtual box).

These commands worked for me:

sudo npm install -g bower
sudo npm install -g gulp
npm install
bower install
npm install node-sass
gulp build scripts --theme="volumio"

Leaving "scripts" off the gulp build line as in the documentation errors for me 100% of the time and only gives me a partial build in dist.  "node-sass" wouldn't install on my PI for some reason, had to be on the x86.  This is a really difficult project to get started on from nothing :)

**Comment by robcee** [comment]
I just ran into this running through setup of Volumio2-UI for the first time. No mention of requiring a virtual box in any of the setup documentation. Kind of a show-stopper as I don't really feel like debugging included node packages on my system to get this working.

**Comment by robcee** [comment]
"process.EventEmitter is deprecated"
https://github.com/times/cardkit/issues/53

Curiously, the version of node installed on my RaspberryPi is 8.11.1 and I'm using 8.11.3 locally. Either the installed socket.io package was patched on the server or there's something funny happening.

**Comment by robcee** [comment]
and the fix:
https://github.com/LearnBoost/websocket.io/issues/55

I'm wondering if the "karma" package needs to be updated or patched.

**Comment by robcee** [comment]
I did a little more digging and learned a bit about the karma package and its dependents. Presumably, this is the unit testing framework for the front-end. It would be nice to have an updated version there, but updating will probably affect whatever unittests are in place, so, it could be an expensive update. Still investigating...

**Comment by tanabi** [comment]
I actually gave up on volumio and made my own player.  While volumio is a total solution and its really cool ... I just wanted something with a next/prev/start/stop button that plays MP3s randomly out of a directory and works nice on a small screen (adafruit's 2.8" tft).

**Comment by volumio** [comment]
Thanks
