### ISSUE TITLE
MPD/MPC

### ISSUE THREAD

**Issue by houndofsound** [volumio/Volumio2-UI#504]
in trying to investigate how mpd is made to update or rescan I compiled and installed a new
version of mpd/mpc. 
unfortunately the Volumio GUI invocation of rescan no longer works.
anyone know how Volumio invokes mpc to make mpd either update or rescan?
I don't see any clue in the mpd sources but the mpd log shows the action of Volumio's Update as likely examining all files, whilst Rescan is adding _and_ removing only named tracks.
curiously though, update doesn't change the database creation timestamp, whereas Rescan does.....

**Comment by xipmix** [comment]
You should probably reopen this issue in https://github.com/volumio/Volumio2 as the rescan etc is done by the backend code, in app/plugins/music_service/mpd/index.js I think. If you are having problems like this, [sending logs](https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html) is always a good start.
