### ISSUE TITLE
wifi icons

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#51]
I haven't actually tested wifi yet, but i noticed in a couple of screenshots of other peoples installs the wifi icon isn't very clear when the signal is low.

I've produced a set of revised icons that are hopefully a bit clearer.

I am away from my machine to commit and create a PR so I have attached them here in case someone else can do it for me.

![0](https://cloud.githubusercontent.com/assets/85802/13462683/6bab799a-e080-11e5-812e-cafb283e256f.png)
![1](https://cloud.githubusercontent.com/assets/85802/13462687/6bb00276-e080-11e5-9250-48126c062357.png)
![2](https://cloud.githubusercontent.com/assets/85802/13462686/6baef4a8-e080-11e5-8b8f-b435680423ed.png)
![3](https://cloud.githubusercontent.com/assets/85802/13462685/6baea6ce-e080-11e5-928a-b3a30f56f25b.png)
![4](https://cloud.githubusercontent.com/assets/85802/13462688/6bb25166-e080-11e5-9396-9a31eac9c888.png)
![5](https://cloud.githubusercontent.com/assets/85802/13462684/6bad37da-e080-11e5-92bd-108827a3b4e9.png)

White on white isn't very clear is it.. they are there.. honest!

[wifiIcons.zip](https://github.com/volumio/Volumio2-UI/files/154910/wifiIcons.zip)

**Comment by kurtommy** [comment]
Great! Thx!
