### ISSUE TITLE
Drives don't mount

### ISSUE THREAD

**Issue by chris-rudmin** [volumio/Volumio2-UI#526]
After a power outage, my pi with Volumio boots faster than my NAS and thus is not mounted on startup. The drive cannot be mounted from the UI (there is no control for this) and thus requires a reboot to mount the drive.

I would suggest a button which would attempt to mount the drive when unmounted. Also I would present a warning when doing database operations (update, rescan) when drives are not mounted, as these actions will effectively delete the database if no mounted drives are found.

**Comment by xipmix** [comment]
Your point about remounting is a good one. I think a UI button to the right of the delete & edit buttons would look ok. One _can_ delete and re-add the drive, but that's pretty nasty.

Nice catch about the db update. I've opened a separate issue on the backend project.
