### ISSUE TITLE
missing semi-colons in log messages in side-menu.directive.js

### ISSUE THREAD

**Issue by robcee** [volumio/Volumio2-UI#537]
[BS] Reloading Browsers...
[11:31:14] webpack is watching for changes
[11:31:57] Time: 1169ms
          Asset    Size  Chunks             Chunk Names
index.module.js  867 kB       0  [emitted]  main

WARNING in ./src/app/components/side-menu/side-menu.directive.js
jshint results in errors
  Missing semicolon. @ line 86 char 32
            console.log(item.state)

  Missing semicolon. @ line 87 char 33
            console.log(item.params)

**Comment by xipmix** [comment]
Hi, is it time to close this?
