### ISSUE TITLE
Capitalization in Plugins Menu

### ISSUE THREAD

**Issue by NellyWhadsDev** [volumio/Volumio2-UI#539]
I've seen this around for a while but have not been able to find even the strings in the code base to try to figure out how to fix it. Image below depicts the inconsistent casing.

I belive it should be every first word capitalized.

![image](https://user-images.githubusercontent.com/8030181/43939317-34a60e90-9c37-11e8-9f56-277d052296c7.png)

**Comment by xipmix** [comment]
strings are in app/i18n/strings_en.json. Please consider fixing any other languages you know also.

**Comment by brianshano** [comment]
PR added for this. 
I figured it could be simply handled with CSS rather than worrying about the original text content.

**Comment by ashthespy** [comment]
FWIW - the source is from each platform's [`plugins.json`](https://github.com/volumio/volumio-plugins/blob/gh-pages/plugins/volumio/armhf/plugins.json)
