### ISSUE TITLE
Touch Icons for Apple, Android & Windows Live Tiles

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#54]
Attached here for @kurtommy 

[touchicons.zip](https://github.com/volumio/Volumio2-UI/files/156799/touchicons.zip)

If you need any more or there are some missing let me know.

**Comment by kurtommy** [comment]
I've updated the path for manifest and touch-icons folder. The icons at the moment are commented out because you have to consider the changing behaviour on play pause stop. You can create a new branch form dev (starting from tomorrow) and update the set

**Comment by apinner** [comment]
Excellent

Would the changing icon for play pause stop have any effect on these icons? The idea was that if you add the UI to the home screen of your device you get a nice clear icon for its native resolution?

**Comment by kurtommy** [comment]
@apinner yep, but the config in manifest, plus metadata override the default favicon. Please un comment metadata in index.html and try it out! Let me know how it goes

**Comment by apinner** [comment]
@kurtommy I'll give it a try later and report back.

These icons do not override the favicon or the favicon change you implemented. They are only used by the devices they address when adding a 'shortcut'.

**Comment by apinner** [comment]
So i have tested it...

Adding to home screen now gives the following experience..

Application name prefilled
http://i.imgur.com/KQ7ceV6.png

The correct icon is used for my screen resolution
http://i.imgur.com/C57CONN.jpg

Clicking on it reloads the UI but with the benefit of having no address bar
http://i.imgur.com/9plqEvM.png

I've also tried testing it with Microsoft Edge and pinning to start, but unfortunately it seems to be ignoring the settings and the tile ends up being blue with the default IE logo.

**Comment by kurtommy** [comment]
does desktop browser's favicon change on play/pause/stop change state?

**Comment by apinner** [comment]
yes it does

**Comment by kurtommy** [comment]
ok, make a new branch and submit a PR

**Comment by apinner** [comment]
I'm going to try and solve the issue with the windows live tile first

**Comment by apinner** [comment]
PR done
