### ISSUE TITLE
Setting up Develompent Environment

### ISSUE THREAD

**Issue by Fosphatic** [volumio/Volumio2-UI#542]
Well some packages seems to be deprecated, would be nice if we could get an update here especially for setting up a development environment. Following the how to leads only to errors, bower is outdated too. Is it possible to move the project to use webpack instead?

**Comment by ChristopherRush** [comment]
Also having this issue.

**Comment by Halloran** [comment]
So it looks like node 6.9.5 is required to get a development environment. Am I missing something? v6.9.5 is > 3 years old now.

**Comment by xipmix** [comment]
Later versions will probably work, 6.x is the minimum. It might be interesting if you want to try 8.x or 9.x and report how it goes.

**Comment by Halloran** [comment]
Installing with node v13.5 (current) results in a pile of errors (the beginning of which are pasted below in case you're interested). Installing < v10 for me looks to be a big time investment so I'm going to pass.

---
> bufferutil@1.2.1 install /Users/John/Projects/Volumio/Volumio2-UI/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.cc:25:30: error: no template named 'Handle' in namespace 'v8'
  static void Initialize(v8::Handle<v8::Object> target)
                         ~~~~^
../src/bufferutil.cc:33:86: error: too few arguments to function call, single
      argument 'context' was not specified
  ...Nan::New<String>("BufferUtil").ToLocalChecked(), t->GetFunction());
                                                      ~~~~~~~~~~~~~~ ^
/Users/John/Library/Caches/node-gyp/13.5.0/include/node/v8.h:6283:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^

**Comment by volumio** [comment]
@Halloran  NVM might be your friend
https://github.com/nvm-sh/nvm
