### ISSUE TITLE
Make error/warning toasts more persistent

### ISSUE THREAD

**Issue by ashthespy** [volumio/Volumio2-UI#551]
Currently all toast messages seem to have a standard timeout of 2 seconds (deduced from:  https://github.com/volumio/Volumio2-UI/blob/462f1b8896ae27db7045e0c2d64a963ae4280d75/src/app/index.config.js#L17-L19

This, along with the `toastr` collapsing pending toasts leads to quick flashes of red and orange when something goes wrong. 
Could we make the warning/error toasts dismissible/ longer timeout?
We could directly provide this override in: https://github.com/volumio/Volumio2-UI/blob/462f1b8896ae27db7045e0c2d64a963ae4280d75/src/app/services/toast-message.service.js#L24-L25
by 
```js
 this.toastr.warning(message, title,{closeButton: true});
```
At least, that is what the [`toastr` docs say](https://github.com/Foxandxss/angular-toastr#toastr-customization)

**Comment by volumio** [comment]
That's a great idea. 
I would suggest:
- Warning messages can last 5 seconds instead of current 2 
Adding those options:
maxOpened: true
preventOpenDuplicates : true
progressBar: true

IMHO toast shoud close itself after a while. If we want persisting errors we can use modals.
What do you think?

**Comment by ashthespy** [comment]
The reasoning behind the close button is that it gives the user the ability to decide how long they wish to leave the error open/closed. If it's a known error, the user can be dismiss it even before the proposed 5 second timeout.  5 seconds should be enough for the user to copy the error message if they feel inclined to investigate it further on the forums/issues. Another idea would be to add `extendedTimeOut` if any attempt is made to interact with the toast?

On the topic of errors, modals are nice, but IMO it would get in the way of the established UX - modals typically pop up as confirmations/reactions to specific task buttons. (Aka update, wizard etc) viz the common error notifications that the plugin system now uses.

That being said - I haven't really played around with all the options, so don't know how they look/feel with the actual UI and UX.

**Comment by volumio** [comment]
I get your point.
What about an option that we can set up via emit to keep the error sticking, and adding a cross icon to close it? 
We could then use this for specific errors, like NAS mounts, so the error will stick until user closes it.
What do you think?

**Comment by ashthespy** [comment]
Yep, NAS mounts and such errors are indeed the use case for these persistent error messages. 
Would you have an example of where this emit event messages are being used? Like in the OTA update modal?

**Comment by volumio** [comment]
No, with OTA we use modals. 
We send out the toast with this:
https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/networkfs/index.js#L424

We could change the type from error to stickingError and do the magic on FE

**Comment by xipmix** [comment]
+1. See also volumio/Volumio2#1602

**Comment by xipmix** [comment]
@ashthespy I can probably test this if you can create a patch.

**Comment by xipmix** [comment]
This is what I tried
```
diff --git a/src/app/index.config.js b/src/app/index.config.js
index b3878ea..c00adce 100644
--- a/src/app/index.config.js
+++ b/src/app/index.config.js
@@ -15,7 +15,9 @@ function config(theme, variant, $logProvider, toastrConfig, themeManagerProvider
   $httpProvider.useApplyAsync(true);
 
   angular.extend(toastrConfig, {
-    timeOut: 2000
+    timeOut: 5000,
+    maxOpen: 10,
+    preventOpenDuplicates: true,
   });
 
 
diff --git a/src/app/services/toast-message.service.js b/src/app/services/toast-message.service.js
index fa50df0..2c962f5 100644
--- a/src/app/services/toast-message.service.js
+++ b/src/app/services/toast-message.service.js
@@ -22,11 +22,14 @@ class ToastMessageService {
         this.toastr.info(message, title);
         break;
       case 'warning':
-        this.toastr.warning(message, title);
+        this.toastr.warning(message, title, {progressBar: true});
         break;
       case 'error':
         this.toastr.error(message, title);
         break;
+      case 'stickingError':
+        this.toastr.error(message, title, {closeButton: true});
+        break;
     }
   }
 
```
but I seem to need to define what a 'stickingError' is somewhere in the backend code? This kind of tweak is not enough, the toast never appears.
```
--- a/app/plugins/system_controller/networkfs/index.js
+++ b/app/plugins/system_controller/networkfs/index.js
@@ -493,7 +493,7 @@ ControllerNetworkfs.prototype.deleteShare = function (data) {
 
             mountutil.umount(mountpoint, false, {"removeDir": true}, function (result) {
                 if (result.error) {
-                    responsemessage = {emit: 'pushToastMessage', data:{ type: 'error', title: self.commandRouter.getI18nString('COMMON.ERROR'), message: self.commandRouter.getI18nString('NETWORKFS.ERROR_UMOUNT')}};
+                    responsemessage = {emit: 'pushToastMessage', data:{ type: 'stickingError', title: self.commandRouter.getI18nString('COMMON.ERROR'), message: self.commandRouter.getI18nString('NETWORKFS.ERROR_UMOUNT')}};
                     self.logger.error("Mount point '" + mountpoint + "' cannot be removed. Error: " + result.error);
                     defer.resolve(responsemessage);
                 }
```

**Comment by ashthespy** [comment]
@xipmix Sorry this slipped past my notifications. 
Have opened up a draft PR - let me know if it works, will rebase on master then..

**Comment by xipmix** [comment]
Unfortunately I am not going to be in a position to help with UI tests for a couple of months at least. Happy to look at code etc. I don't think setting yourself up to do the UI testing is that hard, it will take a bit of persistence though.
