### ISSUE TITLE
Output Device menu bug

### ISSUE THREAD

**Issue by Testato** [volumio/Volumio2-UI#579]
the menu on output device do not work correctly, and maybe should be ideal change it philosophy.

if you have a DAC selected, in the menu do not appear the DAC, so you cannot return to DAC output after your change.

This behaviour is also not consistent, because if you choose other type of DAC it appear, but it is not the correct DAC

Tested on RPI Zero W 
Volumio  2.502

![screenshot from 2018-12-06 13-07-01](https://user-images.githubusercontent.com/6893841/49585491-c577b980-f95e-11e8-9a8d-f011d7a0dd58.png)

![screenshot from 2018-12-06 13-09-17](https://user-images.githubusercontent.com/6893841/49585501-ca3c6d80-f95e-11e8-867a-8b632e5c962e.png)

![screenshot from 2018-12-06 13-50-33](https://user-images.githubusercontent.com/6893841/49585504-cdcff480-f95e-11e8-9698-8af4e6e3a6dd.png)

My proposal:
When the customer select the I2S DAC ON button, the Output Device Menu becomes not selectable

**Comment by volumio** [comment]
Ciao Testato.
This can't be solved as it is. Issue is: we desume available devices from aplay. In this very circumstance you changed a I2S DAC while the module for the previous model is still active (resulting in alsa reporting it on). In this case you need to restart in order to refresh the audio devices

**Comment by Testato** [comment]
Guarda che il comportamento è diverso scheda per scheda, non va bene così
A volte la hai in lista altre no.
Fai delle prove tu stesso.

La soluzione migliore secondo me è come ho scritto sotto disattivare il menu superiore quando so ha in ON la I2S

**Comment by volumio** [comment]
After enabling I2S DACs with some you need to reboot (you won't see in the list)

**Comment by Testato** [comment]
Infatti ho riavviato

**Comment by Testato** [comment]
Ecco i due menu' incriminati Dopo il riavvio,
Come vedi sopra fa apparire una scheda sbagliata
e comunque questo e' solo uno dei due porblemi esposti.

Chiedo formalmente la riapertura della Issue

![screenshot from 2018-12-06 18-53-02](https://user-images.githubusercontent.com/6893841/49602336-7e9eb980-f988-11e8-8e85-c2dd77d6099b.png)

![screenshot from 2018-12-06 18-53-31](https://user-images.githubusercontent.com/6893841/49602339-81011380-f988-11e8-91ed-8820c96a05ba.png)

**Comment by volumio** [comment]
English please. The above happens because in fact the pHAT DAC is using the Hifiberry Driver...

Your suggestion on Telegram IMHO is the soundest thing to do
