### ISSUE TITLE
How to remove a wifi connection?

### ISSUE THREAD

**Issue by KuenzelIT** [volumio/Volumio2-UI#659]
Hi,

I tried to remove my wifi connection, so that Volumio creates a Hotspot. I couldn't find anything in the UI to remove my wifi connection. Is it just me or is that feature missing?

Thanks!

**Comment by xipmix** [comment]
Cog->Network should display:
 * Network status
 * wired network settings (has an on/off button)
 * wireless network settings (has an on/off button)
 * nearby wireless networks
 * dns settings

If any of these are missing can you post a screenshot and a debug logfile?

**Comment by volumio** [comment]
Yes, simply fill a wrong password
