### ISSUE TITLE
iPhone full screen web app not working

### ISSUE THREAD

**Issue by geraldcor** [volumio/Volumio2-UI#666]
When saving volumio.local to the home screen, when opening the app it would be great if it could work in full screen web app mode. `display: standalone` may need to be added to manifest.json. Happy to do a PR if I can figure out the dev loop with angular.

**Comment by volumio** [comment]
Yes thanks, a PR is very appreciated!

**Comment by geraldcor** [comment]
I am having difficulty with `npm install`
node -v 6.9.5
npm -v 3.10.10

npm install times out on multiple packages. I have not yet completed the npm install step. I've installed bower and gulp as well. 

Any recommendations? Do I just have to wait for each timeout to finish?

**Comment by geraldcor** [comment]
Nevermind. The blockage seems to have been fixed.
