### ISSUE TITLE
Inner scroll in various screens

### ISSUE THREAD

**Issue by maxengel** [volumio/Volumio2-UI#667]
In a number of screens, for example, when browsing albums, an inner scroll appears when scrolling down the page. This causes there to be a jerky experience.

**Comment by volumio** [comment]
Thanks Max. Could you please attach some screenshots?

**Comment by maxengel** [comment]
Apologies, please see attached. The best way to reproduce is to hover-over an album cover or artist image (depending on the view) when in the grid layout.
![Screenshot 2019-08-06 at 11 42 16 AM](https://user-images.githubusercontent.com/810989/62554624-69439d00-b83f-11e9-9a4b-74e488200d61.png)
![Screenshot 2019-08-06 at 11 38 52 AM](https://user-images.githubusercontent.com/810989/62554625-69439d00-b83f-11e9-9616-54dc3fc58598.png)
