### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#67]
More of a feature request really. 

Would be nice to be able to switch between a list and a grid view when viewing the music library to show off album art. I was watching this demo of the Naim Mu-So Qb interface yesterday https://www.youtube.com/watch?v=4PScUe8ra6M and thought it looked really smart.

Plex also does something similar; https://www.youtube.com/watch?v=iRuQs7qwJ0c

**Comment by volumio** [comment]
Yes! That would be a nice addition!

**Comment by apinner** [comment]
Yep.. So it just defaults to list view on mobile.

**Comment by apinner** [comment]
Any good as a starting point?

http://plnkr.co/edit/uWw7NuPG0I161mHXZg2r?p=preview
