### ISSUE TITLE
Selecting main Browse page on mobile now auto-selects Search field in Volumio app

### ISSUE THREAD

**Issue by vpooley** [volumio/Volumio2-UI#673]
Hi, I mainly control my Volumio instance from an Android tablet or phone using the Volumio app.
Recently an annoying thing has started to crop up since upgrading to v2.598 and beyond. When navigating to the Browse page from the Player or Queue pages, the Search form is automatically focused and populated with a cursor.
On mobile this means that the keyboard then pops up, annoying if I just wanted to browse and not search. Also some cached search strings drop down, after deleting the Volumio app's app data these cached search strings are gone.

As I said this only seems to have started happening since v2.598 on the Volumio app (which has had no recent updates) and happens on both my Huawei Mediapad tablet and my Samsung Galaxy S9.
This doesn't occur when using mobile or desktop versions of Firefox.

Has the recent inclusion of the Volumio3 UI caused this?
Have a screenshot...
![Screenshot_20190817-100215](https://user-images.githubusercontent.com/10455243/63209332-551d5c80-c0d7-11e9-8603-3667f6d90334.png)

**Comment by gvolt** [comment]
On the local UI (kiosk mode) this occurs as well (tested with Volumio 2.599 on a Raspberry Pi 3B with touch display plugin (1.1.2)). The search field gets the focus and - if matchbox-keybard is installed - the onscreen keyboard appears.

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2-UI/commit/1f9c5ce7ed46207ffa12aa27f71e3fdac049b516
