### ISSUE TITLE
Multiples "Genres" for an album / track

### ISSUE THREAD

**Issue by buzuck** [volumio/Volumio2-UI#677]
Hi,

I find the "Ganres" menu practically unusable. Indeed, I often tag my tracks with multiple genres, with a separator, eg.: "_Folk, Irish Folk_"

On some players, this makes such tracks appear in two separate categories, "_Folk_" and "_Irish Folk_". However, in Volumio, this only creates a single one "_Folk, Irish Folk_", and renders this kind of tagging pretty useless :(

**Comment by buzuck** [comment]
Hello,
Could you provide some info about the reason of this closing? :)

- will not be implemented - too hard?
- relies on mpd?
- other?

Thanks in advance

**Comment by mindist** [comment]
Hello @volumio , @buzuck ,
I'm also very interested for this feature, I found many forums with users that are interested into this feature.
Please can you integrate this feature community would be gratefull.

Best regards

**Comment by buzuck** [comment]
Hi @mindist,
I made some tests after seeing your post. Actually, this feature _is_ implemented. I found tracks under multiple genres categories. The confusing thing is that depending of where you look for information about the separation character, you found multiple answers...
I found that it is either a semi-colon `;` or a comma `,` that is accepted. For Volumio, the comma is the way to go. However, I have no idea if it is a standard way. 

Having an option to define that (or those) characters could be nice :)

It would have been nice of @volumio to say this is implemted, instead of just closing this issue though...

**Comment by mindist** [comment]
Hi @buzuck ,
I think that this is not implemented, at least not correctly as far as I can see.
Lets consider this case, you have only one album on usb drive with genre set as “jazz; pop” on each song (or any other separator can be used), the end result should be when you enter in @volumio and browse genres, that you have two genres to choose, “jazz” and “pop” and click on either lists the same album/songs.
Regards

**Comment by buzuck** [comment]
@mindist : I agree, it is not correctly implemented. Volumio only supports the `,`, not the `;`.
Try using `jazz, pop` instead. On my setup, it seems to be working, even if not thoroughly tested.

Could be nice of @volumio to show up here, because this is really confusing =/

**Comment by mindist** [comment]
@buzuck for me it doesn’t seems to be working with `;` nor with the `,`. 
I attached the screenshot, you can see that I used “Folk;Rock” and “Folk, Rock” and “Folk” doesn’t appear as separate category (genre).

@volumio this feature would be great to organize library
![3A0B1067-5317-4960-9CC3-4648D0436475](https://user-images.githubusercontent.com/3323074/80405720-46708180-88c3-11ea-995a-91b2e2c6da8a.jpeg)

**Comment by buzuck** [comment]
Uh, this is a weird one then. I still have `;` as a separator for a few albums. I just tested changing the separator by a `,`, and the album is now present in all the tagged genres =/ My Volumio version is the `2.729`, released the 18th March.
Apart from that... my audio files are in multiple formats (mp3, ogg, flac), but anyway this shouldn't be an issue.

You could try opening a new issue, maybe this time the devs will do more than just closing the issue without a word... =/

**Comment by volumio** [comment]
Let's use this one. We are in the middle of rewriting the implementation, its good to know about this scenario. @gtriggiano

**Comment by francoestrubia** [comment]
Oh, I can't believe comma is the good one. I have over 15k albums, extremely and properly tagged with musicbrainz picard over the years. Most default configurations on picard are based on semi-colon. So, my genre list something like 300 genres for acoustic, another amount for alternative, experimental, pop, etc etc. 
Any way to change the separator used from the code?  
(my english is bad, not my coder skills. So, point me up).
