### ISSUE TITLE
SSH - Changing password breaks (at least) the plugin management UI

### ISSUE THREAD

**Issue by buzuck** [volumio/Volumio2-UI#678]
I've activated SSH, and then changed the default password (for obvious reasons).

However, this password seems to be required when {un}installing plugins. Here is an extract from the logs :
```
2019-09-14T11:51:44.327Z - info: Uninstall script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins/music_service/youtube/uninstall.sh > /tmp/installog
[sudo] password for volumio: Sorry, try again.
[sudo] password for volumio:
sudo: 1 incorrect password attempt
```
A quick and dirty fix would be to add the management scripts into the `sudoers` file, so they could be launched without asking for a password.
A cleaner approach should be to have two separated accounts, one without login capabilities, in charge of running the server, the UI, with some admin privileges without password on some parts of the system, and a second account, only created when asked for SSH access :-)

**Comment by xipmix** [comment]
Duplicate, see volumio/Volumio2#1192 . If you have more ideas, could you share them there?

**Comment by buzuck** [comment]
Agreed. I did not notice the issue in this repo. I close this one then, thanks! :)
