### ISSUE TITLE
Some bower_components not in found npm registry

### ISSUE THREAD

**Issue by xipmix** [volumio/Volumio2-UI#698]
During the deploy.sh script we see these errors:
```
ERR: Error: Not found : bootstrap-sass-official
ERR: Error: Not found : AngularHammer
ERR: Error: Not found : ngDraggable
ERR: Error: Not found : angular-mailchimp-subscribe
ERR: Error: Not found : angular-country-select
```
These are coming from src/app/themes/volumio/scripts/credits.js.
The reason they are appearing is the packages don't seem to be in the npm registry,
according to 'npm view'.
Some are there, but under different names:
 * angular-hammer
 * ngdraggable

Perhaps those names need updating in the bower.json file?

The errors are minor and only seem to be affecting how the credits pages get filled out;
I'm opening this just in case there is something deeper at play here.
I was testing with nodejs 6.17.1

**Comment by volumio** [comment]
Thanks for reporting, I'm closing since its not a problem, Feel free to update packages names via PR
