### ISSUE TITLE
mobile UI: search hangs Volumio

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2-UI#717]
a search done in desktop UI is fine.
In mobile UI it hangs Volumio : 
`r 05 15:03:53 volumio-rpi4 volumio[8066]: Searching all installed plugins
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin:  , search
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin: mpd , search
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin: last_100 , search
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: Error : CoreCommandRouter::executeOnPlugin: No method [search] in plugin last_100
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin: webradio , search
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: info: CoreCommandRouter::executeOnPlugin: youtube , search
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: TypeError: Cannot read property 'search' of undefined
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at Youtube.doSearch (/data/plugins/music_service/youtube/index.js:636:22)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at Youtube.search (/data/plugins/music_service/youtube/index.js:317:15)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at CoreCommandRouter.executeOnPlugin (/volumio/app/index.js:1067:29)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at CoreMusicLibrary.search (/volumio/app/musiclibrary.js:471:51)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at Socket.<anonymous> (/volumio/app/plugins/user_interface/websocket/index.js:427:42)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at emitTwo (events.js:126:13)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at Socket.emit (events.js:214:7)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at /volumio/node_modules/socket.io/lib/socket.js:503:12
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 05 15:03:53 volumio-rpi4 volumio[8066]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
`

**Comment by volumio** [comment]
This is an issue with youtube plugin, not Volumio itself. going to fix it

**Comment by balbuze** [comment]
ok sorry

**Comment by volumio** [comment]
Nothing to be sorry ;)
