### ISSUE TITLE
RC1 Feedback

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#73]
I'm going to collate all of my feedback for RC1 here. The system works beautifully for me so 90% of my feedback is UI based.

~~1. Volume icon on the mobile UI should go green when active and the volume slider is out.~~
~~2. Next/Back icons should also do the same as above when they are touched on the mobile UI.~~
~~3. Multi room dock image and text not centred.~~
~~4. Consistency with capitals throughout the UI.~~
5. Network status randomly shows red tick.
6. The setting 'Mixer control' is confusing and needs some help documentation.
7. Alarm modal needs some place holder text when no alarms present.
8. Sleep modal inputs are not aligned.
~~9. Suggestion: When hovering over album art in Queue display a play button overlay. Double click works but this is not clear.~~
10. When clicking on another device in the multiroom dock, it displays two of the current device. (Will get a screen shot for this).
11. Is it possible to display the bitrate of a radio stream in the playback knob?
12. I occasionally get partial or failed album art loads.
13. Mute still doesn't work for me.
14. System setting to change the background image would be really really awesome!
~~15. Control a hrefs all need a title tag adding to them for usability.~~
~~16. Album title in now playing coloured volumio green would really satisfy my OCD.~~
17. If you have a lot of items in the queue it can take a long time to load during which the UI is completely unresponsive, Maybe a loading swirl is needed to show something is happening?
18. Need a space after the artist in the play queue, Its currently Artist- Album should be Artist - Album.
19. Input and Buttons when connecting to wireless network are not aligned.
20. If you connect to wired and wireless networks at the same time, the network status columns are not aligned.
21. A force refresh button would be very helpful for wireless networks.
~~22. There is no way to clear a search once you have done one. Need the ability to clear the form and undo the search.~~
~~23. I notice in the search form code there is the magnifier icon but it does not display in the input field.~~
24. The volume knob just does not work! It's horrible to use at the moment, quite a few reports about this already.
25. A button to completely clear the queue would be very helpful.
26. Jump to top button that appears when scrolling through long lists would also be helpful.

Most are pretty minor, overall its a massive step forward from 1.*

Amazing work!!

**Comment by apinner** [comment]
Screenshots for 10.

![multiroom 1](https://cloud.githubusercontent.com/assets/85802/14053257/d566adf6-f2c7-11e5-80b5-dd179b390448.PNG)
![multiroom 2](https://cloud.githubusercontent.com/assets/85802/14053256/d563f2dc-f2c7-11e5-8aab-51c40a9942ad.PNG)

**Comment by balbuze** [comment]
- for multiroom I rename one of my two device but previous is still displayed. And when I switch from one to other the round time is displayed several times (one is add each switch)
- mute button does not work
![multiroomp](https://cloud.githubusercontent.com/assets/12850139/14059383/89584d84-f33f-11e5-9c7f-8e3fbb0265d6.png)

**Comment by apinner** [comment]
22. Something i have just noticed, there is no way to clear a search when browsing the library.

**Comment by apinner** [comment]
I also just got the same issue as @balbuze with the multiple playback knobs being displayed.

**Comment by apinner** [comment]
On the alarm modal, if you have no playlists present then the dropdown box disappears. All of the controls are also very misaligned

![alarm-modal](https://cloud.githubusercontent.com/assets/85802/14316996/fac78d42-fbfd-11e5-963d-273ca9706b44.png)

**Comment by balbuze** [comment]
In mobile UI, when you select an option from a list (like DAC, buffer..) it opens the keyboard.

**Comment by apinner** [comment]
@balbuze It looks like it might be a bug in angular https://github.com/angular-ui/ui-select/issues/818

**Comment by apinner** [comment]
When clicking rescan under My Music it would be nice to have some feedback that something is actually happening. Swirly wheel, progress bar or something.

**Comment by apinner** [comment]
Thinking about how to implement the ability to change the default background.

How about just an smb share to /src/app/themes/volumio/assets/backgrounds

we could just read the contents of that directory for *.png *.jpg etc and populate a dropdown under system settings?

**Comment by volumio** [comment]
We can add the backend for backrounds in a new plugin (maybe under miscellanea, look_and_feel).

We'll have a default background exposed via an express route (something like /background ) so on default it will show the black one. When we change the settings in that plugin we just change the response of that route...
What do you think?

**Comment by apinner** [comment]
Sounds like an even better idea! :+1:

**Comment by volumio** [comment]
I'm flooded with other stuff in this moment... Would you like to start this (either back or FE)... And I'ìll jump in in a couple of days..

**Comment by apinner** [comment]
I'm really short on time myself at the moment, if I get an evening free this week then i'll take a look.

**Comment by volumio** [comment]
We're on the same boat then lol

**Comment by apinner** [comment]
The volume slider on mobile is nice, but tricky to use. There is no feedback or change in the number as you move the slider so you end up guessing where the volume is, so normally takes several attempts to get the right volume.

@kurtommy is it possible for the slider volume number to change with the movement of the slider? It doesn't have to change the volume in real time, just provide some feedback of where the slider is on the scale.

**Comment by JHilsberg** [comment]
In the webradio view is a displaying error with the menu.
![volumio-webradio](https://cloud.githubusercontent.com/assets/5940911/15083919/6425c3d2-13d0-11e6-9769-2fc4902f19ee.PNG)
The menu of the fourth item from top is cut from the bar above.

**Comment by apinner** [comment]
@kurtommy as our angular expert I was wondering if you could offer some advice.

I am working on a set of icons that will show the file format logo in the player control knob. So instead of just mp3 text it will show the mp3 logo, for all of the various formats. For this is have created a load of svg files and our own volumio font (including the logo, note and queue icons).

I have tested this in a dev branch using ng-switch with ng-switch-default being the the original text as a fallback. Which works fine but is there a better way of doing this or is ng-switch the best way?

**Comment by apinner** [comment]
@kurtommy Just trying out some of the recent changes, looking excellent!

One issue, the wireless network list. For some reason the panel title has shifted to the bottom of the panel.

![wireless-problem](https://cloud.githubusercontent.com/assets/85802/15314766/c5be248e-1c0b-11e6-9e55-2ab1a15c48ad.PNG)
