### ISSUE TITLE
Add image on Twitter when sharing

### ISSUE THREAD

**Issue by moniferreir** [volumio/Volumio2-UI#769]
Hello! I've seen when people share the song they are currently listening on twitter, it does not come with any image. The screenshot it how it looks now, no image. Is there any possibility to add image on the tweets?  

<img width="524" alt="Screen Shot 2020-10-02 at 5 28 01 PM" src="https://user-images.githubusercontent.com/72268480/94941098-b7e8d780-04d4-11eb-89a8-45d32eb5920a.png">

Thanks!

**Comment by bencehusi** [comment]
Hey, tweets are referencing the Volumio website (see volumio.com in the tweet) so Twitter looks for images there not on the actual music player (which is not public). The image must be implemented on volumio.org as og:image meta tag.

Closing this issue.
