### ISSUE TITLE
Browse Jump To

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#77]
Just an idea, why don't we add the letters of the alphabet running down the left of right of the screen next to the scroll bar, that makes it easier to jump to a place in the list. This would be especially useful on large libraries.

Attached an image of what I mean. 

![alphabet](https://cloud.githubusercontent.com/assets/85802/14241961/7a2492a6-fa46-11e5-988b-cc2e2a04af13.PNG)

**Comment by volumio** [comment]
Yes, we already thought of that... However it requires a radical rework of both the backend and the frontend...

**Comment by apinner** [comment]
Is it not just adding anchors to the browse table?

**Comment by volumio** [comment]
MMMM, I didn't think about that... clever...

**Comment by apinner** [comment]
Heh, yeah no need to complicate things. Anchor on the first item for each letter, and the alphabet bar just jumps to each anchor.

https://docs.angularjs.org/api/ng/service/$anchorScroll

**Comment by volumio** [comment]
We rewrote the browsing mechanism using pure js, since angular was making everything really slow on long lists..
https://github.com/volumio/Volumio2-UI/commit/5911795555c7f45d04ca373cf05b41830b023395

.Any idea for pure js?

**Comment by apinner** [comment]
@kurtommy is your JS wizard! I am sure anything he can produce will be far more elegant than what I could ever put together.

But this seems like a good starting point http://stackoverflow.com/questions/10221754/javascript-jquery-to-make-anchor-links-down-to-the-first-instance-of-a-specific

We could then just add a class to each folder name and title, something like 'letter-a', 'letter-b'.

**Comment by apinner** [comment]
In addition to this, can we also get some breadcrumbs when browsing.
