### ISSUE TITLE
Support NVM

### ISSUE THREAD

**Issue by franz-josef-kaiser** [volumio/Volumio2-UI#809]
The current NodeJS requirement is `10.22.1`. As I could read in an issue that you are already using NVM, I'd like to suggest to add a `.nvmrc` file to the project root with the sole contents of `10.22.1`, a.k.a the NodeJS-version number. Thanks.

**Comment by volumio** [comment]
Thanks, very good hint! 

https://github.com/volumio/Volumio2-UI/commit/3161c23425502d52872cb876adb2de90abaf3a8e
