### ISSUE TITLE
Add bower as package dev dependency

### ISSUE THREAD

**Issue by franz-josef-kaiser** [volumio/Volumio2-UI#810]
As per the README, Bower is needed to fully set up the project. As not everyone has Bower installed and everyone might have a different version, I'd like to suggest to add it as development dependency and alter the README to run it via `./node_modules/.bin/bower install` instead of calling some globally available alias. Thanks!

**Comment by volumio** [comment]
Upgraded the readme, thanks

In any case you are right that we should call the locally installed bin. A PR making that would be appreciated

**Comment by franz-josef-kaiser** [comment]
@volumio in case you reopen the issue, I can file a related PR.
