### ISSUE TITLE
no graphic elements and album art in the web version ui 

### ISSUE THREAD

**Issue by motogon** [volumio/Volumio2-UI#817]
no graphic elements and album art in the web version ui 
![image](https://user-images.githubusercontent.com/12997195/201963848-bc821ec4-47a9-4ded-b5e4-a93b5803e7c2.png)
![image](https://user-images.githubusercontent.com/12997195/201964043-e1572d47-f111-4b86-aa54-17b1fd276af4.png)

In the local version (hdmi connection) all graphics are displayed correctly. 

![image](https://user-images.githubusercontent.com/12997195/201964589-a449c078-2f58-4621-b0cd-20768863cb6d.png)

![image](https://user-images.githubusercontent.com/12997195/201964875-3d2a0d54-bdc1-486c-b4db-39fa1f3fb053.png)
х86 

this problem with a new installation, immediately 

log http://logs.volumio.org/volumio/b8SoKE0.html

**Comment by motogon** [comment]
Incorrect links are generated 

![image](https://user-images.githubusercontent.com/12997195/202167831-c8884406-ae78-40d8-ac15-a54de7b5d643.png)

**Comment by volumio** [comment]
@mervinderuiter do you have any idea about this?

@motogon did you install some plugin? if yes, which ones?

**Comment by motogon** [comment]
The problem appears immediately after installation, on a clean computer

**Comment by motogon** [comment]
this problem only when accessing via http .

**Comment by volumio** [comment]
From the screenshot we can't really tell what is wrong (too low res) can you upload a bigger res picture or copy paste the logs?
Also, which browser are you using on which OS?

**Comment by volumio** [comment]
Checked your logs, this happens because you have 2 ethernet devices, and the connection happens with eth1 and not eth0.
Can you confirm you have 2 ports?
Can you try plugging ethernet cable to port 1 instead of 2?

Let me know

**Comment by motogon** [comment]
Yes, I have 2 eth ports.
Switched the cable to the other port

**Comment by volumio** [comment]
And?
Does it work?

**Comment by motogon** [comment]
that, problem solved :) 
Thanks

**Comment by motogon** [comment]
![image](https://user-images.githubusercontent.com/12997195/202452548-f4f7b6d1-0982-44d0-b548-bb67cde9e059.png)

But in the application, when you change the track, there is an error 

![image](https://user-images.githubusercontent.com/12997195/202452642-1d8fd0c1-8ed5-4c64-a15f-d50a6e38b27a.png)

**Comment by volumio** [comment]
Great, solving this.

Considering how little the percentage of people is that has 2 eth ports, this is also won't fix

**Comment by motogon** [comment]
![image](https://user-images.githubusercontent.com/12997195/202453242-2120c690-3879-47f3-88e2-c428f8c5dad6.png)

**Comment by motogon** [comment]
I found the problem, the ip was blue :) and the nfs permission was not

**Comment by motogon** [comment]
Thanks for the help with the UI :) 
(I should probably specify in the description that I should use eth0 if there is more than one port in the system)

ps There is still a problem with installation of plugins 

https://github.com/volumio/volumio3-os/issues/55

**Comment by volumio** [comment]
Responded oveer there. For all other questions please refer to community at [community.volumio.org ](https://community.volumio.org/)
