### ISSUE TITLE
Add consume mode option

### ISSUE THREAD

**Issue by gpr511** [volumio/Volumio2-UI#85]
Loving the new UI (RC1), but really miss the consume mode option. Is this due to be added in the next RC or can it be added please.

**Comment by apinner** [comment]
This is where a song is removed from the play queue once it has finished playing?

**Comment by gpr511** [comment]
Yes that's right. I use it all the time, just keep adding tunes to the queue all day.

**Comment by apinner** [comment]
This has now been added.
