### ISSUE TITLE
Suggestion for Multiroom

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2-UI#95]
So this is for discussion really

I was thinking, would the multi room panel be better moved to another menu/location?

This is where my thinking has come from. I add music to the library all the time, but i have trouble keeping track of what is new. Replacing the multi room panel with a Recently Added panel that allows me to scroll through what is new in my library. Or quick access to favourite albums and radio stations without leaving the playback screen.

We could have another icon next to the cog for settings that opens a separate menu with a list of multi room devices. Its current location seems too prominent for what will be a seldom used feature for a lot of people?

**Comment by apinner** [comment]
Managed to do a quick and dirty mockup of what i was thinking of.

![playback-multiroom-icon](https://cloud.githubusercontent.com/assets/85802/14747144/b5558b92-08aa-11e6-8e5e-c5815bf40b4c.jpg)
![playback-multiroom-menu](https://cloud.githubusercontent.com/assets/85802/14747143/b55548a8-08aa-11e6-94bd-2dbc29afdbb2.jpg)

**Comment by volumio** [comment]
That makes a lot of sense... After the plugin thing, this will be done...

**Comment by simonneutert** [comment]
this will be a huge enhancement 👍 
thank you very much 📻
